#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 07.09
(jump-flooding Voronoi / distance transforms).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
The input to a Voronoi/distance transform is just a set of SEED CELLS on a
grid — in robotics, obstacle cells on a costmap. Fully synthesizable, and
ground truth is not stored at all: the demo computes the answer twice (GPU
jump-flooding vs the EXACT brute-force CPU oracle) and checks the JFA's
documented approximation bounds. This file therefore carries only inputs.

What it writes: ../data/sample/jfa_seeds.csv — 64 distinct seed cells on the
demo's fixed 512x512 sample grid:

    S,<id>,x,y      ids sequential from 0; x in [0,512), y in [0,512)

Seeds are drawn uniformly with rejection (no duplicate cells — the GPU
scatter kernel relies on distinctness), seed 42, reproducible byte-for-byte
(python's random.Random is platform-stable).

Usage:
    python make_synthetic.py            # defaults: seed 42, 64 seeds
    python make_synthetic.py --seed 7   # experiments; do not commit
"""

import argparse
import random
import sys
from pathlib import Path

GRID_W = 512   # fixed sample grid — matches the constants in src/main.cu
GRID_H = 512   # (the demo's stable SAMPLE line names 512x512; change together)
DEFAULT_SEEDS = 64


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=int, default=42,
                    help="RNG seed (default 42 — the committed sample's seed)")
    ap.add_argument("--count", type=int, default=DEFAULT_SEEDS,
                    help=f"number of Voronoi seeds (default {DEFAULT_SEEDS})")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "jfa_seeds.csv")
    args = ap.parse_args()

    rng = random.Random(args.seed)

    # Rejection-sample distinct cells; a set of (x, y) enforces the
    # no-duplicates contract the GPU scatter kernel documents.
    cells: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    while len(cells) < args.count:
        xy = (rng.randrange(GRID_W), rng.randrange(GRID_H))
        if xy in seen:
            continue
        seen.add(xy)
        cells.append(xy)

    lines = [
        "# jfa_seeds.csv - SYNTHETIC sample data for project 07.09",
        f"# generated by scripts/make_synthetic.py (python random.Random, seed {args.seed})",
        f"# format: S,<id>,x,y  - one Voronoi seed cell on the {GRID_W}x{GRID_H} sample grid",
        "# robotics reading: each seed is an 'obstacle cell'; the demo's distance",
        "# field is then the clearance map a local planner would consume",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
    ]
    for i, (x, y) in enumerate(cells):
        lines.append(f"S,{i},{x},{y}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes, {args.count} seeds "
          f"on {GRID_W}x{GRID_H}, seed {args.seed}) - labeled SYNTHETIC")
    if args.seed != 42 or args.count != DEFAULT_SEEDS:
        print("note: non-default sample - fine for experiments, do NOT commit this file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
