#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample-data generator for 36.03 (Lattice-robot
kinematics batches).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
This project's "data" is not recordings of anything — it is a BATCH-
GENERATION RECIPE: how many configurations to build, from what seed, what
fraction to corrupt as negative controls, and how many greedy steps the
reconfiguration vignette is allowed. That is exactly the same "scenario, not
recordings" choice project 08.01 makes for its cart-pole start state: the
committed sample is a handful of PARAMETERS, and ../src/main.cu regenerates
the full K=4096-configuration batch deterministically from them every run
(the seeded-accretion algorithm lives in main.cu's generate_config(), NOT
here — this script's only job is to emit the tiny parameter file main.cu
reads at startup).

What this script writes
------------------------
../data/sample/lattice_scenario.csv — four labelled rows:
    K,<int>                    number of configurations in the batch
    SEED,<uint32>               base RNG seed (xorshift32, repo-standard)
    CORRUPT_FRAC,<float>        fraction of K corrupted as negative controls
    VIGNETTE_MAX_STEPS,<int>    greedy reconfiguration step budget

Usage
-----
    python make_synthetic.py                    # defaults: the repo's demo scenario
    python make_synthetic.py --k 4096 --seed 42 --corrupt-frac 0.10 --vignette-steps 600
"""

import argparse
import hashlib
from pathlib import Path

# The fixed default seed and scenario — CLAUDE.md paragraph 12: determinism
# is repo law, so the exact same command produces the exact same bytes on
# every machine. These are also main.cu's compile-time defaults (kDefaultK,
# kDefaultCorruptFrac, kVignetteMaxSteps in kernels.cuh/main.cu) — kept in
# sync deliberately so "the demo's default problem" and "the committed
# sample" describe the same scenario.
DEFAULT_K = 4096
DEFAULT_SEED = 42
DEFAULT_CORRUPT_FRAC = 0.10
DEFAULT_VIGNETTE_STEPS = 600


def make_scenario_csv(k: int, seed: int, corrupt_frac: float, vignette_steps: int, out_path: Path) -> None:
    """Write the four-row scenario CSV described in the module docstring.

    Parameters
    ----------
    k               : number of lattice configurations in the batch (> 0).
    seed            : base xorshift32 seed (main.cu derives one per-config
                      seed per configuration from this value — see
                      ../src/main.cu's generate_config() header comment).
    corrupt_frac    : fraction of k configurations main.cu corrupts as
                      negative controls (half duplicate-position defects,
                      half disconnection defects — ../src/main.cu §5).
    vignette_steps  : greedy reconfiguration step budget for the single-
                      configuration "line -> compact blob" vignette
                      (../src/main.cu §8); a CAP, not a target the greedy
                      heuristic is guaranteed to need or reach.
    out_path        : destination CSV. Parent directories are created if
                      missing.

    Nothing here is a measurement of anything physical — every field is a
    GENERATOR PARAMETER, not a recorded value, so there is no "ground truth"
    to falsify: the file's only job is to make the demo's problem instance
    reproducible byte-for-byte, on any machine, forever.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        f.write("# SYNTHETIC scenario — generated by scripts/make_synthetic.py for project 36.03\n")
        f.write(f"# regenerate: python make_synthetic.py --k {k} --seed {seed} "
                f"--corrupt-frac {corrupt_frac} --vignette-steps {vignette_steps}\n")
        f.write("# This file holds GENERATOR PARAMETERS, not recorded configurations — main.cu's\n")
        f.write("# generate_config() (seeded accretion) regenerates the full K-configuration batch\n")
        f.write("# deterministically from SEED every run (the same 'scenario, not recordings'\n")
        f.write("# pattern project 08.01 uses for its cart-pole start state).\n")
        f.write(f"K,{k}\n")
        f.write(f"SEED,{seed}\n")
        f.write(f"CORRUPT_FRAC,{corrupt_frac}\n")
        f.write(f"VIGNETTE_MAX_STEPS,{vignette_steps}\n")

    digest = hashlib.sha256(out_path.read_bytes()).hexdigest()
    print(f"[make_synthetic] wrote scenario to {out_path}")
    print(f"[make_synthetic]   K={k} SEED={seed} CORRUPT_FRAC={corrupt_frac} VIGNETTE_MAX_STEPS={vignette_steps}")
    print(f"[make_synthetic]   SHA-256: {digest}  (see ../data/README.md)")


def main() -> None:
    """Parse arguments and run the generator. Kept separate from the
    generation function so the logic is importable/testable without
    argparse in the way."""
    script_dir = Path(__file__).resolve().parent
    default_out = script_dir.parent / "data" / "sample" / "lattice_scenario.csv"

    parser = argparse.ArgumentParser(
        description="Generate the tiny synthetic scenario for project 36.03 (Lattice-robot kinematics batches).")
    parser.add_argument("--k", type=int, default=DEFAULT_K,
                        help=f"number of lattice configurations in the batch (default {DEFAULT_K})")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED,
                        help=f"base RNG seed for byte-identical reproducibility (default {DEFAULT_SEED})")
    parser.add_argument("--corrupt-frac", type=float, default=DEFAULT_CORRUPT_FRAC,
                        help=f"fraction of configurations to corrupt as negative controls (default {DEFAULT_CORRUPT_FRAC})")
    parser.add_argument("--vignette-steps", type=int, default=DEFAULT_VIGNETTE_STEPS,
                        help=f"greedy reconfiguration step budget (default {DEFAULT_VIGNETTE_STEPS})")
    parser.add_argument("--out", type=Path, default=default_out,
                        help="output CSV path (default: ../data/sample/lattice_scenario.csv)")
    args = parser.parse_args()

    if args.k <= 0:
        parser.error("--k must be > 0")
    if not (0.0 <= args.corrupt_frac < 1.0):
        parser.error("--corrupt-frac must be in [0, 1)")
    if args.vignette_steps <= 0:
        parser.error("--vignette-steps must be > 0")

    make_scenario_csv(args.k, args.seed, args.corrupt_frac, args.vignette_steps, args.out)


if __name__ == "__main__":
    main()
