#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 22.01
(100k-agent swarm simulator: flocking, pheromone grids, stigmergy).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
A swarm simulator's "dataset" is a SCENARIO, not recordings: how many
agents, how long to simulate, and which seed to spawn them from. That
scenario is this project's committed sample — the agents themselves
(uniform positions, random headings) are spawned inside the demo from the
scenario's seed with the repo's portable xorshift32 generator, and
correctness comes from the brute-force CPU oracle run in lockstep plus the
end-of-run flock statistics, not from stored ground truth. (08.01 set this
scenario-as-data precedent; see ../data/README.md.)

What it writes: ../data/sample/swarm_scenario.csv

    N,n        agent count (the catalog's headline: 100,000)
    STEPS,t    simulation steps at dt = 0.05 s (20 Hz); 300 = 15 s
    SEED,s     xorshift32 spawn seed (uniform positions, random headings)

No RNG runs in THIS script — a scenario is constants (the seed is a
constant too; the randomness happens inside the demo, deterministically).
The file is trivially byte-reproducible; LF line endings are pinned so the
committed bytes and their SHA-256 are identical on every platform.

Usage:
    python make_synthetic.py                       # the committed scenario
    python make_synthetic.py --agents 10000        # experiments; do not commit
"""

import argparse
import sys
from pathlib import Path

# The committed defaults — the exact configuration demo/expected_output.txt
# was written against (changing them changes the demo's stable PROBLEM /
# SCENARIO lines, and the diff will flag it).
DEFAULT_AGENTS = 100000
DEFAULT_STEPS = 300
DEFAULT_SEED = 42


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--agents", type=int, default=DEFAULT_AGENTS,
                    help=f"agent count (default {DEFAULT_AGENTS})")
    ap.add_argument("--steps", type=int, default=DEFAULT_STEPS,
                    help=f"simulation steps at 20 Hz (default {DEFAULT_STEPS} = 15 s)")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED,
                    help=f"xorshift32 spawn seed used by the demo (default {DEFAULT_SEED})")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "swarm_scenario.csv")
    args = ap.parse_args()

    if args.agents < 1 or args.steps < 1 or args.seed < 0:
        ap.error("--agents and --steps must be >= 1, --seed must be >= 0")

    lines = [
        "# swarm_scenario.csv - SYNTHETIC scenario for project 22.01",
        "# generated by scripts/make_synthetic.py (no RNG - a scenario is constants;",
        "# the seed below drives the demo's deterministic xorshift32 spawn)",
        "# N,n     : agent count",
        "# STEPS,t : simulation steps at dt = 0.05 s (20 Hz)",
        "# SEED,s  : spawn seed (uniform positions, random headings, |v| = 1 m/s)",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
        f"N,{args.agents}",
        f"STEPS,{args.steps}",
        f"SEED,{args.seed}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes: N={args.agents}, "
          f"steps={args.steps}, seed={args.seed}) - labeled SYNTHETIC")
    if args.agents != DEFAULT_AGENTS or args.steps != DEFAULT_STEPS or args.seed != DEFAULT_SEED:
        print("note: non-default scenario - fine for experiments, do NOT commit this file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
