#!/usr/bin/env python3
"""make_synthetic.py — synthetic structured-light pattern-stack generator for
project 01.19 (Structured-light decoding: Gray code, phase shift, for 3D
scanners).

Why this script exists (CLAUDE.md §8: synthetic-first)
--------------------------------------------------------
Robotics data can almost always be synthesized with FULL ground truth. A real
structured-light scan needs a calibrated projector-camera rig and a physical
scene; this script instead RENDERS one, analytically, from first principles —
so the demo runs offline, the ground truth (continuous projector column,
depth, and which analytic surface produced each pixel) is EXACT, and the
whole pattern stack regenerates byte-for-byte from one fixed seed.

What it renders — THE SCANNER MODEL (mirrors ../src/kernels.cuh EXACTLY;
if you change one, change the other — main.cu asserts params.csv against
the compiled constants and fails loudly on drift)
--------------------------------------------------------------------------
  * A pinhole CAMERA (kCamW x kCamH) and a PROJECTOR treated as an inverse
    camera, COLUMN AXIS ONLY (kProjCols columns; no row encoding — a fixed
    projector column is a PLANE of light, not a ray — see kernels.cuh).
  * The projector sits BASELINE_M to the right of the camera along +X, same
    orientation (identity rotation) — the simplest legitimate rig, geometry
    identical to a stereo pair with one camera replaced by a projector.
  * A SCENE of three analytic surfaces sharing the camera's ray-casting
    depth-buffer: a tilted BACKGROUND plane, a SPHERE, and a fronto-parallel
    BOX top face (a rectangular patch at constant depth, bounded by a world-
    space footprint — the didactic simplification documented below).
  * A pattern STACK: kGrayBits Gray-code bit planes (direct + photometric
    inverse), kPhaseSteps phase-shift steps, and one all-white/all-black
    reference pair — every pattern rendered under the SAME scene, SAME
    albedo map (including a deliberately LOW-ALBEDO "dark stripe" cohort —
    the confidence-masking honesty test), SAME ambient term, SAME per-pixel
    Gaussian sensor noise, and a mild optical blur.
  * Ground truth per camera pixel: the CONTINUOUS projector column the
    surface point would project to (kInvalidColumnF sentinel where outside
    the projector's illuminated column range — a real, physically honest
    failure mode, not swept under the rug), the true depth (m), and which
    analytic surface produced the pixel (for GRADING the reconstruction
    gates only — never consumed by the decode pipeline itself; see
    ../README.md "Limitations").

Determinism (CLAUDE.md §12; project MACHINE FACTS: stdlib-only, xorshift32,
seed 42) — this script uses NO third-party packages (no numpy) and its own
xorshift32 + Box-Muller generator (the same algorithm used in C++ throughout
this repo, e.g. project 08.01's main.cu) instead of Python's `random` module,
so the noise draws are generated by the exact bit-manipulation algorithm a
learner will also meet in every .cu file here — one fewer thing to context-
switch on when reading this repo end to end.

Usage
-----
    python make_synthetic.py                  # defaults: writes ../data/sample/
    python make_synthetic.py --seed 42 --out ../data/sample
"""

import argparse
import math
import struct
from pathlib import Path

# =============================================================================
# Scanner + code constants — MUST MATCH ../src/kernels.cuh (hand-synced; see
# file header). main.cu reads params.csv and asserts these against the
# compiled kernels.cuh constants before doing anything else with the data.
# =============================================================================
CAM_W, CAM_H = 200, 150                  # camera resolution (px) == kCamW, kCamH
CAM_FX, CAM_FY = 220.0, 220.0            # camera focal length (px) == kCamFx/Fy
CAM_CX, CAM_CY = 100.0, 75.0             # camera principal point (px) == kCamCx/Cy

PROJ_COLS = 128                          # projector columns encoded == kProjCols
PROJ_FX = 180.0                          # projector focal length, column axis == kProjFx
PROJ_CX = 64.0                           # projector principal column == kProjCx

BASELINE_M = 0.12                        # projector offset along camera +X (m) == kBaselineM
# Projector-to-camera rotation is IDENTITY (parallel-axis rig) == kRcp in kernels.cuh.

GRAY_BITS = 7                            # == kGrayBits (2^7 == PROJ_COLS exactly)
PHASE_STEPS = 4                          # == kPhaseSteps
PHASE_PERIOD_COLS = 8.0                  # == kPhasePeriodCols

# =============================================================================
# Scene — three analytic surfaces sharing one depth buffer (camera-frame,
# meters). Tuned (see the diagnostic printout this script emits) so every
# surface: (a) is inside the camera's field of view, (b) stays inside the
# projector's kProjCols-column illuminated range so the hybrid pipeline has
# real correspondences to find, and (c) produces a comfortably measurable
# sphere radius and box step height relative to the scanner's depth
# precision (THEORY.md derives dz ~ z^2/(f*b)*d_disparity ~ 1 mm here).
# =============================================================================
SURF_NONE, SURF_BACKGROUND, SURF_SPHERE, SURF_BOX = 0, 1, 2, 3

# Background: a plane written as an explicit HEIGHT FIELD Z = Z0 + AX*X (no
# tilt in Y) — algebraically simpler than a general plane-normal intersection
# and exactly equivalent for a plane that is a function of camera rays (every
# camera ray hits it exactly once). AX = tan(10 deg): a visible-but-gentle tilt.
BG_Z0 = 0.75              # depth at X=0 (m)
BG_AX = 0.1763269807      # dZ/dX slope == tan(10 deg)
BG_ALBEDO = 0.75          # diffuse reflectance, unitless in [0,1]

# Sphere: ordinary ray-sphere intersection (the one surface here that is NOT
# a height field — a deliberate contrast so the renderer exercises a real
# quadratic, not just closed-form division).
SPHERE_C = (0.02, -0.02, 0.55)   # center (m), camera frame
SPHERE_R = 0.09                  # radius (m)
SPHERE_ALBEDO = 0.65

# Box: the didactic simplification named in README/THEORY — we model only
# the box's TOP FACE as a fronto-parallel plane (constant depth) bounded by a
# world-space rectangle. This renders a clean, unambiguous depth STEP without
# needing a full 3-D box (side walls, self-occlusion, multiple depth layers)
# that would teach nothing extra about structured light itself.
BOX_Z = 0.58                       # constant depth of the top face (m)
BOX_X_RANGE = (0.10, 0.24)         # world-space X footprint (m)
BOX_Y_RANGE = (-0.10, 0.04)        # world-space Y footprint (m)
BOX_ALBEDO = 0.55

# Dark-albedo stripe cohort — the confidence-masking honesty test (README/
# THEORY "dark_stripe"). Defined directly in CAMERA PIXEL space (simplest,
# most legible footprint) over the background plane's lower band.
DARK_STRIPE_ROWS = (95, 118)       # camera row range [start, end)
DARK_STRIPE_COLS = (30, 175)       # camera col range [start, end)
DARK_ALBEDO = 0.05                 # near-black — the whole point of the cohort

# Radiometry: captured = AMBIENT + albedo * pattern_signal[0,1] * GAIN + noise.
AMBIENT = 20.0            # constant ambient offset (intensity counts, 0-255 scale)
GAIN = 180.0              # projector-illumination-to-counts gain
NOISE_SIGMA = 3.0         # per-pixel, per-frame Gaussian sensor read noise (counts)
BLUR_RADIUS = 1           # 3x3 box blur (mild optical/defocus blur), applied to
                           # the full (ambient + signal) image before noise —
                           # simulates lens PSF acting on the whole scene equally.

DEFAULT_SEED = 42


# =============================================================================
# xorshift32 + Box-Muller — the repo's portable deterministic RNG (see file
# header). A pure-Python re-implementation of the exact algorithm used in
# this repo's C++ demos (e.g. 08.01's main.cu): three xor/shift steps producing
# a 32-bit state, top 24 bits turned into a uniform float, two uniforms turned
# into one Gaussian via Box-Muller. Bit-for-bit reproducible on any platform
# because it uses only integer XOR/shift (no libm RNG, no floating-point RNG
# state) until the very last float conversion.
# =============================================================================
class Xorshift32:
    def __init__(self, seed: int):
        self.state = seed & 0xFFFFFFFF
        if self.state == 0:               # xorshift is degenerate at state 0 (stays 0 forever)
            self.state = 0x9E3779B9        # any nonzero constant works; golden-ratio bit pattern by convention

    def next_u32(self) -> int:
        x = self.state
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= (x >> 17)
        x ^= (x << 5) & 0xFFFFFFFF
        self.state = x & 0xFFFFFFFF
        return self.state

    def uniform01(self) -> float:
        # Top 24 bits -> (0,1], matching the C++ demos' uniform01() exactly in
        # SPIRIT (never exactly 0, safe for log() in Box-Muller below).
        return (self.next_u32() >> 8) * (1.0 / 16777216.0) + (0.5 / 16777216.0)

    def gaussian(self, sigma: float) -> float:
        u1 = self.uniform01()
        u2 = self.uniform01()
        z = math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)
        return sigma * z


# =============================================================================
# Ray casting — one camera pixel -> the winning surface's (t, surface_id,
# albedo), where t is the ray parameter AND the depth (since our ray
# direction is built with dz = 1 exactly: P = t*(dx,dy,1), so P.z == t).
# =============================================================================
def camera_ray(col: int, row: int):
    """Pixel-center convention (MUST match kernels.cuh / triangulate_kernel):
    dx = (col+0.5-cx)/fx, dy = (row+0.5-cy)/fy, implicit dz = 1."""
    dx = (col + 0.5 - CAM_CX) / CAM_FX
    dy = (row + 0.5 - CAM_CY) / CAM_FY
    return dx, dy


def intersect_background(dx: float, dy: float):
    """Closed-form height-field intersection: Z = BG_Z0 + BG_AX*X, X = t*dx,
    Z = t  =>  t = BG_Z0 / (1 - BG_AX*dx). Returns None if the ray is
    (near-)parallel to the plane or the intersection is behind the camera."""
    denom = 1.0 - BG_AX * dx
    if denom <= 1e-6:
        return None
    t = BG_Z0 / denom
    return t if t > 0.0 else None


def intersect_box(dx: float, dy: float):
    """Constant-depth plane Z = BOX_Z => t = BOX_Z directly (dz = 1). Valid
    only where the resulting (X,Y) falls inside the box's world footprint —
    the "fronto-parallel patch bounded by a rectangle" simplification."""
    t = BOX_Z
    x, y = t * dx, t * dy
    if BOX_X_RANGE[0] <= x <= BOX_X_RANGE[1] and BOX_Y_RANGE[0] <= y <= BOX_Y_RANGE[1]:
        return t
    return None


def intersect_sphere(dx: float, dy: float):
    """Standard ray-sphere quadratic: |t*D - C|^2 = r^2 with D=(dx,dy,1),
    ray origin at the camera's optical center (0,0,0). Returns the smallest
    POSITIVE root, or None if the ray misses or both roots are behind us."""
    dz = 1.0
    cx, cy, cz = SPHERE_C
    lx, ly, lz = -cx, -cy, -cz               # O - C, O = origin
    a = dx * dx + dy * dy + dz * dz
    b = 2.0 * (dx * lx + dy * ly + dz * lz)
    c = lx * lx + ly * ly + lz * lz - SPHERE_R * SPHERE_R
    disc = b * b - 4.0 * a * c
    if disc < 0.0:
        return None
    sq = math.sqrt(disc)
    t1 = (-b - sq) / (2.0 * a)
    t2 = (-b + sq) / (2.0 * a)
    lo, hi = (t1, t2) if t1 < t2 else (t2, t1)
    if lo > 1e-6:
        return lo
    if hi > 1e-6:
        return hi
    return None


def cast_pixel(col: int, row: int):
    """Depth-buffer resolve for ONE camera pixel: intersect all three
    surfaces, keep the SMALLEST positive t (closest to the camera — normal
    z-buffer visibility), return (X, Y, Z, surface_id, albedo). Every pixel
    resolves to SOME surface here because the background plane is an
    (approximately) infinite height field within this camera's FOV."""
    dx, dy = camera_ray(col, row)
    candidates = []
    t_bg = intersect_background(dx, dy)
    if t_bg is not None:
        candidates.append((t_bg, SURF_BACKGROUND))
    t_box = intersect_box(dx, dy)
    if t_box is not None:
        candidates.append((t_box, SURF_BOX))
    t_sph = intersect_sphere(dx, dy)
    if t_sph is not None:
        candidates.append((t_sph, SURF_SPHERE))
    if not candidates:
        return None
    t, surf = min(candidates, key=lambda p: p[0])
    x, y, z = t * dx, t * dy, t

    if surf == SURF_BACKGROUND:
        in_stripe = (DARK_STRIPE_ROWS[0] <= row < DARK_STRIPE_ROWS[1] and
                     DARK_STRIPE_COLS[0] <= col < DARK_STRIPE_COLS[1])
        albedo = DARK_ALBEDO if in_stripe else BG_ALBEDO
    elif surf == SURF_SPHERE:
        albedo = SPHERE_ALBEDO
    else:
        albedo = BOX_ALBEDO
    return x, y, z, surf, albedo


def projector_column(x: float, z: float):
    """The projector's own pinhole equation, COLUMN AXIS ONLY (kernels.cuh
    file header): a 3-D point (in camera/world frame) projects to projector
    column up = fxp * Xp/Zp + cxp, where (Xp,Zp) is the point re-expressed in
    the projector's frame: Pproj = R_cp^T (P - t_cp); with R_cp = IDENTITY
    this is just P - t_cp, and Zp = Z (translation is pure-X). Returns the
    CONTINUOUS column, or None if it falls outside [0, PROJ_COLS) — the
    projector genuinely does not illuminate that point (documented, honest
    failure mode carried through as the kInvalidColumnF sentinel)."""
    xp = x - BASELINE_M
    zp = z
    if zp <= 1e-6:
        return None
    up = PROJ_FX * (xp / zp) + PROJ_CX
    if up < 0.0 or up >= PROJ_COLS:
        return None
    return up


# =============================================================================
# Pattern rendering
# =============================================================================
def gray_code(v: int) -> int:
    """Standard binary-to-Gray-code map: g = v XOR (v >> 1). Bijective over
    N-bit values; consecutive integers' Gray codes differ in EXACTLY one bit
    (the property THEORY.md proves and the gray_vs_binary gate measures)."""
    return v ^ (v >> 1)


def blur3x3(img, w: int, h: int):
    """Mild separable box blur (radius 1, edge-replicated border) — models
    lens/projector defocus smearing scene radiance across neighboring camera
    pixels BEFORE the sensor samples it. Deliberately "mild": strong enough
    that decode must cope with the same optics real scanners have, gentle
    enough that it does not itself scramble the Gray code boundaries the
    gray_vs_binary lesson is measuring (that lesson uses its own, separate,
    analytically-controlled blur model — see ../src/kernels.cu)."""
    def clamp(v, lo, hi):
        return lo if v < lo else (hi if v > hi else v)

    # horizontal pass
    tmp = [0.0] * (w * h)
    for r in range(h):
        base = r * w
        for c in range(w):
            s = 0.0
            n = 0
            for dc in (-1, 0, 1):
                cc = clamp(c + dc, 0, w - 1)
                s += img[base + cc]
                n += 1
            tmp[base + c] = s / n
    # vertical pass
    out = [0.0] * (w * h)
    for r in range(h):
        for c in range(w):
            s = 0.0
            n = 0
            for dr in (-1, 0, 1):
                rr = clamp(r + dr, 0, h - 1)
                s += tmp[rr * w + c]
                n += 1
            out[r * w + c] = s / n
    return out


def write_pgm(path: Path, img_u8, w: int, h: int):
    """Write a binary PGM (P5), maxval 255 — the simplest widely-readable
    lossless grayscale format, and the one every project in this repo's
    perception domain uses for single-channel artifacts."""
    with path.open("wb") as f:
        f.write(f"P5\n{w} {h}\n255\n".encode("ascii"))
        f.write(bytes(img_u8))


def render_pattern(signal01, in_fov, albedo, w: int, h: int, rng: Xorshift32):
    """Turn a per-pixel [0,1] pattern signal into a captured, noisy, blurred,
    quantized 8-bit image, per the radiometric model in the file header:
        ideal = AMBIENT + albedo * signal01 * GAIN   (0 where out of FOV)
        blurred = blur3x3(ideal)
        captured = clamp(round(blurred + gaussian(NOISE_SIGMA)), 0, 255)
    """
    n = w * h
    ideal = [0.0] * n
    for i in range(n):
        s = signal01[i] if in_fov[i] else 0.0
        ideal[i] = AMBIENT + albedo[i] * s * GAIN
    blurred = blur3x3(ideal, w, h)
    out = bytearray(n)
    for i in range(n):
        v = blurred[i] + rng.gaussian(NOISE_SIGMA)
        iv = int(round(v))
        if iv < 0:
            iv = 0
        elif iv > 255:
            iv = 255
        out[i] = iv
    return out


def generate(seed: int, out_dir: Path, verbose: bool = True):
    out_dir.mkdir(parents=True, exist_ok=True)
    w, h, n = CAM_W, CAM_H, CAM_W * CAM_H

    # ---- 1) Ray-cast every pixel once: (X,Y,Z,surface,albedo,truth_col) ----
    xs = [0.0] * n
    ys = [0.0] * n
    zs = [0.0] * n
    surf = [SURF_NONE] * n
    albedo = [0.0] * n
    truth_col = [None] * n
    in_fov = [False] * n

    surf_counts = {SURF_NONE: 0, SURF_BACKGROUND: 0, SURF_SPHERE: 0, SURF_BOX: 0}
    fov_count = 0
    for row in range(h):
        for col in range(w):
            i = row * w + col
            hit = cast_pixel(col, row)
            if hit is None:
                surf_counts[SURF_NONE] += 1
                continue
            x, y, z, s, a = hit
            xs[i], ys[i], zs[i], surf[i], albedo[i] = x, y, z, s, a
            surf_counts[s] += 1
            uc = projector_column(x, z)
            if uc is not None:
                truth_col[i] = uc
                in_fov[i] = True
                fov_count += 1

    if verbose:
        print(f"[make_synthetic] surface pixel counts: "
              f"background={surf_counts[SURF_BACKGROUND]} sphere={surf_counts[SURF_SPHERE]} "
              f"box={surf_counts[SURF_BOX]} none={surf_counts[SURF_NONE]}")
        print(f"[make_synthetic] pixels inside projector FOV: {fov_count} / {n} "
              f"({100.0 * fov_count / n:.1f}%)")
        cols_seen = [c for c in truth_col if c is not None]
        if cols_seen:
            print(f"[make_synthetic] truth column range: [{min(cols_seen):.2f}, {max(cols_seen):.2f}] "
                  f"of [0, {PROJ_COLS})")

    # ---- 2) Render the Gray-code stack: N direct + N inverse frames --------
    rng = Xorshift32(seed)
    manifest = []   # (filename, description) pairs for params.csv / README

    for bit in range(GRAY_BITS):
        direct01 = [0.0] * n
        inverse01 = [0.0] * n
        for i in range(n):
            if not in_fov[i]:
                continue
            col_idx = int(round(truth_col[i]))
            col_idx = 0 if col_idx < 0 else (PROJ_COLS - 1 if col_idx >= PROJ_COLS else col_idx)
            g = gray_code(col_idx)
            b = (g >> (GRAY_BITS - 1 - bit)) & 1
            direct01[i] = float(b)
            inverse01[i] = float(1 - b)
        img_d = render_pattern(direct01, in_fov, albedo, w, h, rng)
        img_i = render_pattern(inverse01, in_fov, albedo, w, h, rng)
        fname_d = f"gray_b{bit}_direct.pgm"
        fname_i = f"gray_b{bit}_inverse.pgm"
        write_pgm(out_dir / fname_d, img_d, w, h)
        write_pgm(out_dir / fname_i, img_i, w, h)
        manifest.append((fname_d, f"Gray-code bit {bit} (0=MSB), direct illumination"))
        manifest.append((fname_i, f"Gray-code bit {bit} (0=MSB), photometric inverse"))

    # ---- 3) Render the phase-shift stack: 4 steps ---------------------------
    for k in range(PHASE_STEPS):
        sig01 = [0.0] * n
        for i in range(n):
            if not in_fov[i]:
                continue
            frac = truth_col[i] % PHASE_PERIOD_COLS
            phi = 2.0 * math.pi * frac / PHASE_PERIOD_COLS
            sig01[i] = 0.5 + 0.5 * math.cos(phi - k * (math.pi / 2.0))
        img = render_pattern(sig01, in_fov, albedo, w, h, rng)
        fname = f"phase_s{k}.pgm"
        write_pgm(out_dir / fname, img, w, h)
        manifest.append((fname, f"phase-shift step {k}/4 (offset {k}*pi/2)"))

    # ---- 4) All-white / all-black reference frames --------------------------
    white01 = [1.0 if in_fov[i] else 0.0 for i in range(n)]
    black01 = [0.0] * n
    img_w = render_pattern(white01, in_fov, albedo, w, h, rng)
    img_b = render_pattern(black01, in_fov, albedo, w, h, rng)
    write_pgm(out_dir / "ref_white.pgm", img_w, w, h)
    write_pgm(out_dir / "ref_black.pgm", img_b, w, h)
    manifest.append(("ref_white.pgm", "all-white reference (projector full-on)"))
    manifest.append(("ref_black.pgm", "all-black reference (projector full-off)"))

    # ---- 5) Ground-truth binaries: column (f32), depth (f32), surface (u8) -
    with (out_dir / "truth_column.bin").open("wb") as f:
        f.write(struct.pack(f"<{n}f", *[(truth_col[i] if truth_col[i] is not None else -1.0) for i in range(n)]))
    with (out_dir / "truth_depth.bin").open("wb") as f:
        f.write(struct.pack(f"<{n}f", *zs))
    with (out_dir / "truth_surface.bin").open("wb") as f:
        f.write(struct.pack(f"<{n}B", *surf))

    # ---- 6) params.csv — scanner geometry, scene truth, provenance ---------
    xc = 0.5 * (BOX_X_RANGE[0] + BOX_X_RANGE[1])
    bg_z_at_box = BG_Z0 + BG_AX * xc
    step_height_truth = bg_z_at_box - BOX_Z

    params_path = out_dir / "params.csv"
    with params_path.open("w", newline="", encoding="utf-8") as f:
        f.write("# SYNTHETIC data - generated by scripts/make_synthetic.py for project 01.19\n")
        f.write(f"# regenerate: python make_synthetic.py --seed {seed}\n")
        f.write("# key,value  (units in the key name; all geometry is camera-frame == world-frame)\n")
        rows = [
            ("cam_w_px", CAM_W), ("cam_h_px", CAM_H),
            ("cam_fx_px", CAM_FX), ("cam_fy_px", CAM_FY),
            ("cam_cx_px", CAM_CX), ("cam_cy_px", CAM_CY),
            ("proj_cols", PROJ_COLS), ("proj_fx_px", PROJ_FX), ("proj_cx_px", PROJ_CX),
            ("baseline_m", BASELINE_M),
            ("gray_bits", GRAY_BITS), ("phase_steps", PHASE_STEPS), ("phase_period_cols", PHASE_PERIOD_COLS),
            ("seed", seed),
            ("bg_z0_m", BG_Z0), ("bg_ax_slope", BG_AX), ("bg_albedo", BG_ALBEDO),
            ("sphere_cx_m", SPHERE_C[0]), ("sphere_cy_m", SPHERE_C[1]), ("sphere_cz_m", SPHERE_C[2]),
            ("sphere_radius_m_truth", SPHERE_R), ("sphere_albedo", SPHERE_ALBEDO),
            ("box_z_m", BOX_Z),
            ("box_x_min_m", BOX_X_RANGE[0]), ("box_x_max_m", BOX_X_RANGE[1]),
            ("box_y_min_m", BOX_Y_RANGE[0]), ("box_y_max_m", BOX_Y_RANGE[1]),
            ("box_albedo", BOX_ALBEDO), ("step_height_m_truth", step_height_truth),
            ("dark_stripe_row_min", DARK_STRIPE_ROWS[0]), ("dark_stripe_row_max", DARK_STRIPE_ROWS[1]),
            ("dark_stripe_col_min", DARK_STRIPE_COLS[0]), ("dark_stripe_col_max", DARK_STRIPE_COLS[1]),
            ("dark_albedo", DARK_ALBEDO),
            ("ambient_counts", AMBIENT), ("gain_counts", GAIN), ("noise_sigma_counts", NOISE_SIGMA),
            ("blur_radius_px", BLUR_RADIUS),
            ("surf_background_pixels", surf_counts[SURF_BACKGROUND]),
            ("surf_sphere_pixels", surf_counts[SURF_SPHERE]),
            ("surf_box_pixels", surf_counts[SURF_BOX]),
            ("surf_none_pixels", surf_counts[SURF_NONE]),
            ("projector_fov_pixels", fov_count),
        ]
        for k, v in rows:
            f.write(f"{k},{v}\n")

    if verbose:
        print(f"[make_synthetic] step height truth (box vs local background): {step_height_truth * 1000.0:.1f} mm")
        print(f"[make_synthetic] wrote {len(manifest) + 3} files to {out_dir} (seed={seed}, labeled SYNTHETIC)")

    return {
        "manifest": manifest,
        "surf_counts": surf_counts,
        "fov_count": fov_count,
        "step_height_truth": step_height_truth,
    }


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    default_out = script_dir.parent / "data" / "sample"

    parser = argparse.ArgumentParser(
        description="Generate the synthetic structured-light pattern stack for project 01.19.")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED,
                        help=f"RNG seed for byte-identical reproducibility (default {DEFAULT_SEED})")
    parser.add_argument("--out", type=Path, default=default_out,
                        help="output directory (default: ../data/sample)")
    args = parser.parse_args()

    generate(args.seed, args.out)


if __name__ == "__main__":
    main()
