#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample-data generator for 25.01
(Li-ion electrochemical (SPM) solver on GPU + 3D pack thermal simulation +
cooling-design sweeps).

Why this script exists (CLAUDE.md §8: synthetic-first)
--------------------------------------------------------
There is no real, redistributable "24-cell robot battery pack" dataset to
download — and even if there were, licensing real cell electrochemistry data
is exactly the kind of thing CLAUDE.md §8 says to avoid. Every number this
script writes is a SYNTHETIC, hand-chosen TEACHING PARAMETER: shaped to be
physically plausible (real orders of magnitude for diffusivities, activation
energies, thermal conductivities) but never claimed to match any real cell,
pack, or dataset. `../README.md` and `../data/README.md` both repeat this
label; so does every row of the generated CSV itself (comment header below).

What this script generates
---------------------------
One CSV, data/sample/pack_scenario.csv, with one row per problem-definition
group (THERMAL, CELL_DIMS, ANODE, CATHODE, ELEC, MISSION, SEG x4, SWEEP_H) —
the exact row-labeled format src/main.cu's load_scenario() parses (documented
there and in ../data/README.md). There is no RNG here at all: every value is
a literal, deliberately chosen constant, so "regenerate" reproduces the exact
same file byte-for-byte on any machine — determinism by construction, not by
seeding (CLAUDE.md §12).

Where the numbers came from (brief; the full derivation with the resulting
capacity/SOC/thermal-rise arithmetic lives in THEORY.md "The math" and
"The problem"):
  * ANODE/CATHODE geometry+kinetics: graphite-like anode, NMC-like cathode,
    particle radii and diffusivities at realistic orders of magnitude for
    Li-ion solid-state diffusion (1e-14..1e-13 m^2/s), activation energies
    in the commonly-cited 20-50 kJ/mol range.
  * OCV curves are NOT stored in this file — they are synthetic closed-form
    polynomials hard-coded in src/main.cu (ocv_anode/ocv_cathode), documented
    there and in THEORY.md, because they are FUNCTIONS, not scenario data.
  * THERMAL: anisotropic kx=ky (in-plane) >> kz (through-plane), the real
    qualitative anisotropy of a wound/stacked cell (THEORY.md "The problem").
  * MISSION: a 120 s AMR duty cycle (accelerate/cruise/idle/regen-charge)
    repeated 10x to fill the 1200 s (20 min) mission, currents chosen so the
    pack's SOC swings a realistic partial-cycle ~15-40% (not a full 0-100%
    cycle — an AMR on shift does not deep-cycle every 20 minutes) while still
    generating enough heat to make the cooling-design comparison interesting
    (THEORY.md documents the exact energy arithmetic behind this choice).
  * SWEEP_H: six convective coefficients spanning natural convection (air,
    ~10 W/(m^2 K)) to an aggressive liquid cold plate (~500 W/(m^2 K)).

Usage
-----
    python make_synthetic.py                                  # writes ../data/sample/pack_scenario.csv
    python make_synthetic.py --out ../data/sample/pack_scenario.csv
"""

import argparse
from pathlib import Path


def write_scenario_csv(out_path: Path) -> None:
    """Write the single committed scenario file. No RNG, no seed: every
    value below is a literal synthetic teaching constant (see module
    docstring); "regenerating" reproduces this file byte-for-byte.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# SYNTHETIC scenario for project 25.01 — generated by scripts/make_synthetic.py",
        "# regenerate: python make_synthetic.py",
        "# Every numeric value below is a hand-chosen SYNTHETIC teaching parameter",
        "# (plausible orders of magnitude; NOT fit to any real cell or dataset).",
        "# See ../data/README.md for units/fields and THEORY.md for the derivations",
        "# and the SOC/thermal-rise arithmetic behind the mission currents below.",
        "#",
        "# THERMAL: rho_cp[J/(m3 K)], kx,ky,kz[W/(m K)], T_init[K], T_coolant[K]",
        "THERMAL,2.0e6,25.0,25.0,3.0,298.15,298.15",
        "#",
        "# CELL_DIMS: one cell's footprint Lx,Ly,Lz [m] (tiles exactly into the",
        "# 4x3x2 pack -> 32x24x16 thermal grid, 8 voxels/cell/axis)",
        "CELL_DIMS,0.08,0.06,0.12",
        "#",
        "# ANODE / CATHODE: R_p[m],D25[m^2/s],Ea_D[J/mol],c_max[mol/m^3],",
        "#                  c0_frac[-],i0_ref[A/m^2],Ea_k[J/mol],A_surf[m^2]",
        "# (graphite-like anode; NMC-like cathode — see module docstring)",
        "ANODE,6.0e-6,3.0e-14,35000,30000,0.75,15.0,30000,2.5",
        "CATHODE,5.0e-6,1.0e-14,25000,48000,0.40,10.0,30000,3.0",
        "#",
        "# ELEC: R_ohm[Ohm] — per-cell lumped internal ohmic resistance",
        "ELEC,0.10",
        "#",
        "# MISSION: dt_thermal[s], n_sub[-] (electrochemistry substeps per",
        "# thermal step), duration_s[s]",
        "MISSION,0.1,5,1200",
        "#",
        "# SEG: kind[label only], duration_s[s], current_A[A] (+ = discharge).",
        "# One 120 s AMR duty cycle, repeated 10x to fill the 1200 s mission.",
        "SEG,accelerate,15,20.0",
        "SEG,cruise,65,7.0",
        "SEG,idle,20,1.0",
        "SEG,charge,20,-10.0",
        "#",
        "# SWEEP_H: 6 convective coefficients [W/(m^2 K)], natural convection",
        "# to an aggressive liquid cold plate; crossed with {bottom,side} in",
        "# main.cu for the 12-design sweep.",
        "SWEEP_H,10,25,50,100,250,500",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"[make_synthetic] wrote {out_path} ({len(lines)} lines, labeled SYNTHETIC, no RNG)")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    default_out = script_dir.parent / "data" / "sample" / "pack_scenario.csv"

    parser = argparse.ArgumentParser(
        description="Generate the committed synthetic scenario for project 25.01.")
    parser.add_argument("--out", type=Path, default=default_out,
                        help="output CSV path (default: ../data/sample/pack_scenario.csv)")
    args = parser.parse_args()

    write_scenario_csv(args.out)


if __name__ == "__main__":
    main()
