#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 20.01
(GelSight/DIGIT processing: contact patch, shear field via optical flow,
slip detection in real time).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
A tactile sensor's "dataset" here is a SCENARIO, not recordings — exactly
08.01's precedent for a controller's task definition. Every one of the
demo's 100 frames is RENDERED IN-CODE, deterministically, by ../src/main.cu
(render_frame()) from two things: this tiny committed scenario file, and the
fixed physical model (image size, marker grid, Hertzian contact physics,
Cattaneo-Mindlin stick/slip law, phase lengths) that lives ONCE in
../src/kernels.cuh so the renderer and every ground-truth gate agree on the
same numbers. Nothing about the SCENE needs a downloaded or hand-labeled
dataset: the contact footprint, the marker displacement field, and the
slip-onset frame are all exact, closed-form consequences of the physics
model, so ground truth is free and perfect by construction (no laser scan,
no hand annotation, no sensor calibration rig required) — the same synthetic
advantage 08.01/01.02 lean on.

What it writes: ../data/sample/tactile_scenario.csv

    INDENTER,sphere|edge   which indenter shape presses into the gel (the
                           catalog bullet's "a sphere and later an edge" —
                           see ../src/main.cu's contact_distance_px()); the
                           COMMITTED scenario uses sphere (the demo's
                           ground-truth gates are calibrated for it — see
                           README "Limitations & honesty" for the edge mode's
                           documented, reduced scope).
    SEED,n                 the RNG seed for the gel's FIXED micro-texture
                           noise (deterministic hash, not per-frame — see
                           kernels.cuh; the same seed reproduces the same
                           bytes on any machine).

Usage:
    python make_synthetic.py                       # the committed scenario
    python make_synthetic.py --indenter edge        # experiment; do NOT commit
    python make_synthetic.py --seed 7               # experiment; do NOT commit
"""

import argparse
import sys
from pathlib import Path

DEFAULT_INDENTER = "sphere"
DEFAULT_SEED = 42


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--indenter", choices=["sphere", "edge"], default=DEFAULT_INDENTER,
                    help=f"indenter shape (default {DEFAULT_INDENTER}; the committed sample's "
                         "ground-truth gates are calibrated for sphere only)")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED,
                    help=f"gel micro-texture noise seed (default {DEFAULT_SEED})")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "tactile_scenario.csv")
    args = ap.parse_args()

    if args.seed < 0:
        ap.error("--seed must be >= 0 (main.cu reads it as an unsigned integer)")

    lines = [
        "# tactile_scenario.csv - SYNTHETIC scenario for project 20.01",
        "# generated by scripts/make_synthetic.py (deterministic hash noise - no RNG state)",
        "# INDENTER,sphere|edge : which indenter shape presses into the gel this run",
        "# SEED,n               : fixed-texture noise seed (see ../src/kernels.cuh, ../src/main.cu)",
        "# every OTHER number (image size, marker grid, contact physics, phase lengths) is",
        "# single-sourced in ../src/kernels.cuh - this file only selects the two knobs above.",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
        f"INDENTER,{args.indenter}",
        f"SEED,{args.seed}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes: indenter={args.indenter}, "
          f"seed={args.seed}) - labeled SYNTHETIC")
    if args.indenter != DEFAULT_INDENTER or args.seed != DEFAULT_SEED:
        print("note: non-default scenario - fine for experiments, do NOT commit this file "
              "(the committed demo/expected_output.txt gates assume the default sphere scenario)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
