#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample-data generator for 17.08 (Regolith DEM simulation for wheels and scoops).

TEMPLATE PLACEHOLDER — replace the generation logic with this project's real synthesizer.
TODO(scaffold): generate this project's actual sample data (with full ground truth where
applicable), document every output field in ../data/README.md, and keep the output TINY.

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
Robotics data can almost always be synthesized with full ground truth — poses, depth, flow,
contacts — so synthetic generation is this repository's DEFAULT data source. Every project
ships a generator like this one so the committed sample under ../data/sample/ is (a) tiny,
(b) license-clean, and (c) reproducible bit-for-bit from a FIXED SEED. Synthetic data is
labeled synthetic everywhere it appears.

What the placeholder does
-------------------------
Writes a small deterministic CSV of x/y float vectors (the same *kind* of data the SAXPY
placeholder demo computes on) into ../data/sample/saxpy_sample.csv, so learners can see the
pattern: argparse -> fixed seed -> deterministic bytes -> labeled synthetic output.
Note: the placeholder demo itself generates its input IN MEMORY (see make_input() in
../src/main.cu) and does not read this file — the CSV exists to demonstrate the workflow.

Usage
-----
    python make_synthetic.py                 # defaults: n=256, seed=42
    python make_synthetic.py --n 1024 --seed 7 --out ../data/sample/saxpy_sample.csv
"""

import argparse
import csv
import random
from pathlib import Path

# The fixed default seed. Determinism is repo law (CLAUDE.md paragraph 12): the same
# command must produce the same bytes on every machine, so samples are reproducible
# and diffs are meaningful. 42 carries no significance beyond tradition.
DEFAULT_SEED = 42

# Keep the committed sample tiny (CLAUDE.md paragraph 8): 256 rows of two floats is
# ~6 KB — more than enough to demonstrate the format.
DEFAULT_N = 256


def make_saxpy_csv(n: int, seed: int, out_path: Path) -> None:
    """Write n rows of synthetic (x, y) float pairs to out_path as CSV.

    Parameters
    ----------
    n        : number of rows (> 0). Unitless placeholder data.
    seed     : RNG seed. Same seed + same n => byte-identical file, every run,
               every platform (Python's Mersenne Twister is specified, so
               random.Random(seed) is cross-platform deterministic).
    out_path : destination CSV. Parent directories are created if missing.

    The file starts with '#'-prefixed comment lines labeling it SYNTHETIC and
    recording the exact regeneration command — provenance travels with the data.
    TODO(scaffold): replace with the real project's synthesis (and real units/frames).
    """
    rng = random.Random(seed)  # local RNG: never touch the global seed (avoids spooky action between scripts)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # newline='' is the csv-module requirement on Windows (prevents doubled \r\n);
    # utf-8 is the repo-wide encoding.
    with out_path.open("w", newline="", encoding="utf-8") as f:
        # Comment header: label + provenance + regeneration command (CLAUDE.md paragraph 8).
        f.write("# SYNTHETIC data — generated by scripts/make_synthetic.py for project 17.08\n")
        f.write(f"# regenerate: python make_synthetic.py --n {n} --seed {seed}\n")
        f.write("# columns: x (float, unitless placeholder), y (float, unitless placeholder)\n")
        writer = csv.writer(f)
        writer.writerow(["x", "y"])
        for _ in range(n):
            # uniform() draws are deterministic given the seeded local RNG above.
            # Repr via format() with fixed precision keeps the file byte-stable.
            x = rng.uniform(0.0, 1.0)   # matches the magnitude range main.cu uses
            y = rng.uniform(1.0, 2.0)
            writer.writerow([f"{x:.8f}", f"{y:.8f}"])

    print(f"[make_synthetic] wrote {n} rows to {out_path} (seed={seed}, labeled SYNTHETIC)")


def main() -> None:
    """Parse arguments and run the generator. Kept separate from the generation
    function so the logic is importable/testable without argparse in the way."""
    # Resolve the default output RELATIVE TO THIS SCRIPT, not the CWD, so the
    # command works no matter where it is invoked from.
    script_dir = Path(__file__).resolve().parent
    default_out = script_dir.parent / "data" / "sample" / "saxpy_sample.csv"

    parser = argparse.ArgumentParser(
        description="Generate the tiny synthetic sample for project 17.08 (Regolith DEM simulation for wheels and scoops).")
    parser.add_argument("--n", type=int, default=DEFAULT_N,
                        help=f"number of rows to generate (default {DEFAULT_N}; keep the sample tiny)")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED,
                        help=f"RNG seed for byte-identical reproducibility (default {DEFAULT_SEED})")
    parser.add_argument("--out", type=Path, default=default_out,
                        help="output CSV path (default: ../data/sample/saxpy_sample.csv)")
    args = parser.parse_args()

    if args.n <= 0:
        parser.error("--n must be > 0")

    # TODO(scaffold): replace this call with the real project's synthesis pipeline.
    make_saxpy_csv(args.n, args.seed, args.out)


if __name__ == "__main__":
    main()
