#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 08.01
(MPPI controller, cart-pole teaching core).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
A controller's "dataset" is a TASK, not recordings: where the plant starts
and how long the controller must run. That scenario is this project's
committed sample — everything else (exploration noise, rollouts, the plant
itself) is generated inside the demo from fixed seeds, and correctness comes
from the CPU rollout oracle plus the closed-loop success check, not from
stored ground truth.

What it writes: ../data/sample/cartpole_scenario.csv

    X0,p,pdot,theta,thetadot   start state (SI units; theta=pi = hanging
                               straight down, the classic swing-up start)
    STEPS,n                    closed-loop control steps at 50 Hz

The default scenario is THE cart-pole benchmark: start at rest, hanging
(theta = pi exactly), cart at the origin; 400 steps = 8 seconds — enough
for swing-up (~2-3 s with the tuned weights) plus a long balancing tail the
success check can be strict about. No RNG is involved (a scenario is
constants); the file is trivially byte-reproducible.

Usage:
    python make_synthetic.py                    # the committed scenario
    python make_synthetic.py --theta0 2.8       # experiments; do not commit
"""

import argparse
import sys
from pathlib import Path

PI = 3.14159265358979323846


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--theta0", type=float, default=PI,
                    help="initial pole angle in rad (default pi = hanging down)")
    ap.add_argument("--steps", type=int, default=400,
                    help="closed-loop control steps at 50 Hz (default 400 = 8 s)")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "cartpole_scenario.csv")
    args = ap.parse_args()

    lines = [
        "# cartpole_scenario.csv - SYNTHETIC scenario for project 08.01",
        "# generated by scripts/make_synthetic.py (no RNG - a scenario is constants)",
        "# X0,p,pdot,theta,thetadot : start state, SI units, theta=0 upright / pi hanging",
        "# STEPS,n                  : closed-loop control steps at 50 Hz",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
        f"X0,0,0,{args.theta0:.9g},0",
        f"STEPS,{args.steps}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes: theta0={args.theta0:.6g}, "
          f"steps={args.steps}) - labeled SYNTHETIC")
    if abs(args.theta0 - PI) > 1e-12 or args.steps != 400:
        print("note: non-default scenario - fine for experiments, do NOT commit this file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
