#!/usr/bin/env python3
"""make_synthetic.py - synthetic sample generator for project 01.12
(Visual servoing: image-Jacobian control loop entirely on GPU).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
-----------------------------------------------------------------
Like project 08.01's MPPI controller, this project's "dataset" is a TASK
SIZE, not recordings: how many independent closed IBVS loops to simulate
(K) and how fine a grid to sample for the basin-map artifact (BASIN_G).
Everything else this project needs is generated INSIDE the demo executable
from documented, fixed constants and a fixed RNG seed:

  * the target geometry and goal camera pose  -> compile-time constants in
    src/kernels.cuh (kTargetHalfSize, kGoalStandoff) and the closed-form
    build_target_and_goal_cpu() in src/reference_cpu.cpp;
  * the K loops' initial camera poses across the three designed cohorts
    (nominal / decay / retreat, see kernels.cuh "COHORTS") -> host-side
    xorshift32 in generate_batch_init_poses_cpu(), base seed 42;
  * the basin-map grid's initial poses -> generate_basin_grid_poses_cpu(),
    no RNG (a grid is constants).

This script writes ONLY the tiny scenario file that names the batch size
and grid resolution — the equivalent of 08.01's cartpole_scenario.csv.

What it writes: ../data/sample/ibvs_scenario.csv

    K,n           number of independent IBVS loops in the main batch
    BASIN_G,g     basin-map grid side (g*g loops, translation-only slice)

The default scenario (K=4096, BASIN_G=64) is what every number quoted in
README.md/THEORY.md/demo/expected_output.txt was measured against; running
the demo with a different --k/--basin-g changes the PROBLEM/SCENARIO lines
(and the gate floors were tuned for the default — see src/main.cu).

Usage:
    python make_synthetic.py                 # the committed scenario
    python make_synthetic.py --k 1024         # experiments; do not commit
"""

import argparse
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--k", type=int, default=4096,
                    help="number of independent IBVS loops in the main batch (default 4096)")
    ap.add_argument("--basin-g", type=int, default=64,
                    help="basin-map grid side; grid has basin-g^2 loops (default 64)")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "ibvs_scenario.csv")
    args = ap.parse_args()

    lines = [
        "# ibvs_scenario.csv - SYNTHETIC scenario for project 01.12",
        "# generated by scripts/make_synthetic.py (no RNG here - a scenario is constants;",
        "# the K loops' actual initial poses are generated INSIDE the demo executable from a",
        "# fixed xorshift32 seed - see src/reference_cpu.cpp generate_batch_init_poses_cpu)",
        "# K,n         : number of independent closed IBVS loops in the main batch",
        "# BASIN_G,g   : basin-map grid side (g*g translation-only loops for basin_map.ppm)",
        "# target geometry, goal pose, and controller constants live in src/kernels.cuh",
        "# (kTargetHalfSize, kGoalStandoff, kLambda, kDampingMu, kDt, kMaxSteps, kConvergeEps)",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
        f"K,{args.k}",
        f"BASIN_G,{args.basin_g}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes: K={args.k}, BASIN_G={args.basin_g}) "
          f"- labeled SYNTHETIC")
    if args.k != 4096 or args.basin_g != 64:
        print("note: non-default scenario - fine for experiments, do NOT commit this file "
              "(the gate floors documented in README.md/THEORY.md were tuned for K=4096, BASIN_G=64)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
