#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 10.03
(Massively parallel robot sim: Isaac-Gym-style, one robot, 10,000 environments).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
This project's "dataset" is a FARM SCENARIO, not recordings: how many
environments, how long to run them, the domain-randomization envelope, and
the fixed balance-controller gains. That scenario is this project's
committed sample -- everything else (per-environment mass/length draws,
initial angles, and every mid-run reset) is generated INSIDE the demo, on
the GPU, from the scenario's SEED field, and correctness comes from the
CPU oracle comparison plus the physics-invariant gates, not from stored
ground truth.

What it writes: ../data/sample/farm_scenario.csv

    N,n                  number of environments in the full farm
    T_FARM,t              ticks to run the full farm for
    EPISODE_CAP,c          ticks per episode before a successful reset
    SEED,s                 base RNG seed (per-env streams derive from this)
    DR_MASS_CART,r          +/- fractional domain-randomization range on mass_cart
    DR_MASS_POLE,r          +/- fractional domain-randomization range on mass_pole
    DR_LEN,r                +/- fractional domain-randomization range on pole_half_len
    THETA0_RANGE,r          +/- rad range for the initial-angle draw at every reset
    KX,KXD,KTH,KTHD         fixed pole-placement balance-controller gains

No RNG is involved in GENERATING this file (a scenario is constants, the
same principle 08.01's cartpole_scenario.csv uses); the committed defaults
match kernels.cuh's kDefault* constants exactly, so this file is trivially
byte-reproducible and the numbers it documents are the numbers the code
would use even if this file went missing.

Usage:
    python make_synthetic.py                    # the committed scenario
    python make_synthetic.py --n 2000            # experiments; do not commit
"""

import argparse
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n", type=int, default=10000, help="environments in the full farm (default 10000)")
    ap.add_argument("--t-farm", type=int, default=1000, help="ticks to run the full farm (default 1000)")
    ap.add_argument("--episode-cap", type=int, default=200, help="ticks per episode before a cap-reset (default 200)")
    ap.add_argument("--seed", type=int, default=42, help="base RNG seed (default 42)")
    ap.add_argument("--dr-mass-cart", type=float, default=0.20, help="+/- fractional randomization on mass_cart (default 0.20)")
    ap.add_argument("--dr-mass-pole", type=float, default=0.30, help="+/- fractional randomization on mass_pole (default 0.30)")
    ap.add_argument("--dr-len", type=float, default=0.15, help="+/- fractional randomization on pole_half_len (default 0.15)")
    ap.add_argument("--theta0-range", type=float, default=0.15, help="+/- rad initial-angle draw range (default 0.15)")
    ap.add_argument("--kx", type=float, default=12.0, help="balance gain on x (default 12.0)")
    ap.add_argument("--kxd", type=float, default=14.0, help="balance gain on xdot (default 14.0)")
    ap.add_argument("--kth", type=float, default=73.0, help="balance gain on theta (default 73.0)")
    ap.add_argument("--kthd", type=float, default=19.0, help="balance gain on thdot (default 19.0)")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "farm_scenario.csv")
    args = ap.parse_args()

    lines = [
        "# farm_scenario.csv - SYNTHETIC scenario for project 10.03",
        "# generated by scripts/make_synthetic.py (no RNG - a scenario is constants)",
        "# N            : environments in the full farm",
        "# T_FARM       : ticks to run the full farm for (dt = 0.02 s, see src/kernels.cuh)",
        "# EPISODE_CAP  : ticks per episode before a SUCCESSFUL (cap) reset",
        "# SEED         : base RNG seed; every env's stream derives from this + its index",
        "# DR_MASS_CART, DR_MASS_POLE, DR_LEN : +/- fractional domain-randomization ranges",
        "#                (drawn ONCE per environment at farm init; see THEORY.md)",
        "# THETA0_RANGE : +/- rad range the initial pole angle is drawn from at EVERY reset",
        "# KX,KXD,KTH,KTHD : fixed linear state-feedback balance-controller gains",
        "#                   (N/m, N.s/m, N/rad, N.s/rad - pole-placement derivation in THEORY.md)",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
        f"N,{args.n}",
        f"T_FARM,{args.t_farm}",
        f"EPISODE_CAP,{args.episode_cap}",
        f"SEED,{args.seed}",
        f"DR_MASS_CART,{args.dr_mass_cart:.6g}",
        f"DR_MASS_POLE,{args.dr_mass_pole:.6g}",
        f"DR_LEN,{args.dr_len:.6g}",
        f"THETA0_RANGE,{args.theta0_range:.6g}",
        f"KX,{args.kx:.6g}",
        f"KXD,{args.kxd:.6g}",
        f"KTH,{args.kth:.6g}",
        f"KTHD,{args.kthd:.6g}",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size} bytes: N={args.n}, T_FARM={args.t_farm}, "
          f"episode_cap={args.episode_cap}) - labeled SYNTHETIC")
    is_default = (args.n == 10000 and args.t_farm == 1000 and args.episode_cap == 200 and args.seed == 42
                 and args.dr_mass_cart == 0.20 and args.dr_mass_pole == 0.30 and args.dr_len == 0.15
                 and args.theta0_range == 0.15 and args.kx == 12.0 and args.kxd == 14.0
                 and args.kth == 73.0 and args.kthd == 19.0)
    if not is_default:
        print("note: non-default scenario - fine for experiments, do NOT commit this file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
