#!/usr/bin/env python3
"""make_synthetic.py — synthetic sample generator for project 09.01
(batched forward kinematics).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
---------------------------------------------------------------
Kinematics is the best-case for synthetic data: a robot MODEL is just a list
of numbers, and joint configurations are just angles — full ground truth
comes free (the demo computes poses twice, GPU vs CPU oracle, and compares;
the oracle is the ground truth, so this file carries only INPUTS).

What it writes: ../data/sample/fk_sample.csv with two row types (format
shared with the loader in src/main.cu; data/README.md documents each field):

    J,<idx>,tx,ty,tz,qw,qx,qy,qz,ax,ay,az    one row per joint, chain order
    Q,<idx>,q0,...,q5                        one joint configuration (rad)

The robot: a SYNTHETIC generic 6-DoF anthropomorphic arm (yaw base, two
pitch joints for shoulder/elbow, roll-pitch-roll wrist) with round-number
link lengths summing to a ~0.9 m reach. It resembles the industrial-arm
ARCHETYPE on purpose and no vendor's product: every number below is invented
for teaching. Fixed rotations are all identity (the joint AXES carry the
geometry instead) — easy to reason about by hand, which is the point of a
sample. Configurations are uniform in (-pi, pi], seed 42, reproducible
byte-for-byte (python's random.Random is platform-stable).

Usage:
    python make_synthetic.py                 # defaults: seed 42, 64 configs
    python make_synthetic.py --seed 7        # experiments; do not commit
"""

import argparse
import math
import random
import sys
from pathlib import Path

# The synthetic arm, one tuple per joint, in chain order:
#   (t (m), fixed-rotation quaternion (w,x,y,z), unit joint axis)
# Geometry story: base yaw (Z) lifted 0.15 m off the mounting plate; shoulder
# pitch (Y) 0.10 m above it; 0.35 m upper arm to the elbow pitch (Y); 0.30 m
# forearm to a roll (X); short 0.08/0.07 m wrist links with pitch (Y) and
# roll (X). All frames right-handed, x-forward/y-left/z-up (repo convention).
SYNTHETIC_ARM = [
    ((0.0, 0.0, 0.15), (1.0, 0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),   # J0 base yaw
    ((0.0, 0.0, 0.10), (1.0, 0.0, 0.0, 0.0), (0.0, 1.0, 0.0)),   # J1 shoulder pitch
    ((0.35, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0), (0.0, 1.0, 0.0)),   # J2 elbow pitch
    ((0.30, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),   # J3 forearm roll
    ((0.08, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0), (0.0, 1.0, 0.0)),   # J4 wrist pitch
    ((0.07, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),   # J5 wrist roll
]

DEFAULT_CONFIGS = 64   # sample size: smaller than one 256-thread block on
# purpose (exercises the ragged tail); the demo's in-memory batch stage
# covers the many-block case.


def fmt(values) -> str:
    """CSV-format floats at 9 significant digits (round-trips FP32 exactly)."""
    return ",".join(f"{v:.9g}" for v in values)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=int, default=42,
                    help="RNG seed for the configurations (default 42 — the "
                         "committed sample's seed; non-default output must not be committed)")
    ap.add_argument("--configs", type=int, default=DEFAULT_CONFIGS,
                    help=f"number of joint configurations (default {DEFAULT_CONFIGS})")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "data" / "sample" / "fk_sample.csv")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    nj = len(SYNTHETIC_ARM)

    lines = [
        "# fk_sample.csv - SYNTHETIC sample data for project 09.01",
        f"# generated by scripts/make_synthetic.py (python random.Random, seed {args.seed})",
        "# J,<idx>,tx,ty,tz,qw,qx,qy,qz,ax,ay,az  - robot model row (see data/README.md)",
        "# Q,<idx>,q0..q5                          - joint configuration, radians in (-pi, pi]",
        "# robot: synthetic generic 6-DoF arm - an archetype, NO vendor's product",
        "# license: same as the repository (MIT) - fully synthetic, no external source",
    ]

    # Model rows, chain order — the loader in main.cu preserves file order.
    for idx, (t, quat, axis) in enumerate(SYNTHETIC_ARM):
        lines.append(f"J,{idx},{fmt(t)},{fmt(quat)},{fmt(axis)}")

    # Configuration rows: uniform angles in (-pi, pi], one fixed stream.
    for k in range(args.configs):
        q = [math.pi * (1.0 - 2.0 * rng.random()) for _ in range(nj)]
        lines.append(f"Q,{k},{fmt(q)}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:   # LF pinned (.gitattributes agrees)
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out} ({args.out.stat().st_size / 1024.0:.1f} KiB, "
          f"{nj} joints, {args.configs} configs, seed {args.seed}) - labeled SYNTHETIC")
    if args.seed != 42 or args.configs != DEFAULT_CONFIGS:
        print("note: non-default sample - fine for experiments, do NOT commit this file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
