// ===========================================================================
// kernels.cuh — interface for project 12.01
//               TensorRT deployment with custom CUDA pre/post kernels:
//               NMS, argmax decode, keypoint extraction
//
// Role in the project
// -------------------
// The CONTRACT between main.cu (orchestration + GPU-vs-CPU verification),
// kernels.cu (the GPU kernels), reference_cpu.cpp (the CPU oracle twin of
// the WHOLE pipeline), and tensorrt_path.cpp (the optional, off-by-default
// TensorRT engine path). Everything all four must agree on — tensor
// layouts, the fixed "network" architecture, the weight-file format, the
// detection record, and every tuning constant — is defined HERE, once
// (CLAUDE.md §12).
//
// SCOPE (read this before anything else — CLAUDE.md §5 dependency policy)
// -------------------------------------------------------------------
// This is the repo's first HEAVY-SDK project. TensorRT is allowed ONLY
// because this project is explicitly about deploying to it. The DEFAULT
// build (this file, kernels.cu, reference_cpu.cpp, main.cu) needs ZERO
// TensorRT headers or libraries — it is a small, hand-rolled, fully-taught
// CUDA inference pipeline that stands on its own. TensorRT itself only
// appears in tensorrt_path.cpp, entirely behind `#ifdef USE_TENSORRT`
// (off by default — see README "Build" for the exact opt-in steps). The
// fallback path below is NOT a stub: it is this project's didactic heart.
// The catalog bullet's three named post-processing kernels — NMS, argmax
// decode, keypoint extraction — are implemented for real, in plain CUDA,
// wrapped around a tiny hand-rolled "detector" whose weights are SYNTHETIC
// (deterministic, fixed, generated once by scripts/make_synthetic.py) —
// this project teaches DEPLOYMENT plumbing, not training (that is 12.06's
// job; see README "Limitations & honesty").
//
// THE FIXED "NETWORK" (a deterministic tensor program, not a trained model)
// ---------------------------------------------------------------------
// Input: an 80x80 RGB test image (data/sample/test_scene.ppm) containing a
// few solid-colored rectangles ("red" or "blue") on a mid-gray, mildly
// dithered background — synthetic, generated by scripts/make_synthetic.py.
//
//   preprocess:  HWC uint8 [80,80,3]
//                  -> bilinear resize -> [64,64,3]
//                  -> per-channel normalize ((x-mean)/std)
//                  -> transpose HWC->CHW -> float32 [3,64,64]
//   conv1:       3->2 ch, 3x3, stride 2, pad 1, ReLU      -> [2,32,32]
//                  ch0 = "redness"  =  avg(R_norm) - avg(B_norm)
//                  ch1 = "blueness" =  avg(B_norm) - avg(R_norm)
//   conv2:       2->2 ch, 3x3, stride 2, pad 1, ReLU      -> [2,16,16]
//                  further 3x3/stride-2 average-pool of each channel
//   head (1x1):  2->6 ch, 1x1, stride 1, pad 0, LINEAR    -> [6,16,16]
//                  ch0 = class0 (red)  score  = redness_feature  - bias
//                  ch1 = class1 (blue) score  = blueness_feature - bias
//                  ch2..5 = tx,ty,tw,th box-regression (weights ZERO in
//                           this synthetic net — see the box-decode note
//                           below; the ANCHOR ARITHMETIC is still real and
//                           general, only the learned refinement is absent)
//
// Every weight above is a small INTEGER-like constant (thirds, ones,
// zeros) chosen by hand so the whole forward pass is checkable with a
// pencil (THEORY.md works two full examples). This is a deliberate,
// documented scoping choice: see README "Limitations & honesty".
//
// THE POST-PROCESSING PIPELINE (the catalog bullet's three kernels, plus
// the score-threshold/box-decode step that sits between the first two)
// ---------------------------------------------------------------------
//   1. argmax_decode        — one thread per GRID cell (16x16=256): argmax
//                              over the kNumClasses score channels ->
//                              best_class[cell], best_score[cell].
//   2. threshold_box_decode — one thread per GRID cell: if best_score >
//                              threshold, decode a box via ANCHOR ARITHMETIC
//                              (fixed anchor, cell-relative center) and
//                              atomically append a Detection to a compacted
//                              candidate array (GPU stream compaction).
//   3. (host) sort candidates by score descending (stable, tie-broken by
//              cell index — see main.cu) — trivial O(N log N) bookkeeping,
//              kept on the host by the same "don't GPU-ify trivial scalar
//              work" reasoning 08.01 documents.
//   4. iou_matrix            — ALL-PAIRS IoU of the (small, sorted)
//                              candidate set — the genuinely parallel part
//                              of NMS — one thread per (i,j) pair.
//   5. (host) greedy suppression scan over the precomputed IoU matrix —
//              INHERENTLY SEQUENTIAL (survivor i suppresses j only if i
//              itself survived), so it is not fought into a kernel; see
//              THEORY.md "The GPU mapping" for the parallelism-tension
//              discussion the task explicitly asks to document.
//   6. keypoint_extract       — one thread per SURVIVING detection: a
//                              local-window argmax over the winning class's
//                              own score map (reused as a CenterNet-style
//                              heatmap; see README "Prior art") refines a
//                              keypoint location near the detection.
//
// TENSOR LAYOUT CONVENTION — CHW, row-major, C-outermost (documented once):
//   A [C,H,W] tensor is stored as tensor[c*H*W + y*W + x], float32. This is
//   the layout every deep-learning inference engine (TensorRT included)
//   expects at its input binding — which is WHY the preprocessing kernel's
//   last act is the HWC->CHW TRANSPOSE: camera drivers and image codecs
//   deliver HWC (interleaved pixels, cache-friendly for display); inference
//   engines want CHW (planar, cache-friendly for per-channel convolution
//   taps). This transpose is the single most common "gotcha" wired into
//   real deployment code, and one of the two things a custom preprocessing
//   kernel MUST get right (the other is the resize's coordinate convention
//   — see kernels.cu).
//
// Read this after: README.md, THEORY.md.  Read this before: kernels.cu.
// ===========================================================================
#ifndef PROJECT_KERNELS_CUH
#define PROJECT_KERNELS_CUH

#include <cstdint>   // uint8_t — the raw image byte type

// ===========================================================================
// SECTION 1 — fixed scene / architecture constants (the single source of
// truth every file includes; CLAUDE.md §12 "one place" rule).
// ===========================================================================

// ---- source image (the committed sample) ---------------------------------
constexpr int kSrcW = 80;      // data/sample/test_scene.ppm width, px
constexpr int kSrcH = 80;      // ...height, px — the loader in main.cu
                                // REQUIRES the file to match exactly (strict
                                // loader discipline, CLAUDE.md §12).

// ---- network input (after the preprocessing kernel) -----------------------
constexpr int kNetW = 64;      // network input width, px
constexpr int kNetH = 64;      // network input height, px
// Resize scale, source -> network space (0.8 exactly: 80*0.8 = 64). Kept as
// a named constant because the artifact writer (main.cu) maps detection
// boxes back to SOURCE pixels for drawing by dividing by this scale.
constexpr float kNetScale = static_cast<float>(kNetW) / static_cast<float>(kSrcW);

// ---- normalization (per-channel, same mean/std for R,G,B) -----------------
// Chosen so the mid-gray (128,128,128) background normalizes to exactly
// 0.0 in every channel — the "the background carries no signal" property
// the conv1 weights below depend on (THEORY.md works the arithmetic).
constexpr float kPixelMean = 128.0f;
constexpr float kPixelStd  = 64.0f;

// ---- conv1: 3 -> 2 channels, 3x3, stride 2, pad 1, ReLU --------------------
constexpr int kConv1In     = 3;
constexpr int kConv1Out    = 2;
constexpr int kConv1K      = 3;
constexpr int kConv1Stride = 2;
constexpr int kConv1Pad    = 1;
constexpr int kConv1OutH   = (kNetH + 2 * kConv1Pad - kConv1K) / kConv1Stride + 1;  // 32
constexpr int kConv1OutW   = (kNetW + 2 * kConv1Pad - kConv1K) / kConv1Stride + 1;  // 32

// ---- conv2: 2 -> 2 channels, 3x3, stride 2, pad 1, ReLU --------------------
constexpr int kConv2In     = kConv1Out;
constexpr int kConv2Out    = 2;
constexpr int kConv2K      = 3;
constexpr int kConv2Stride = 2;
constexpr int kConv2Pad    = 1;
constexpr int kConv2OutH   = (kConv1OutH + 2 * kConv2Pad - kConv2K) / kConv2Stride + 1;  // 16
constexpr int kConv2OutW   = (kConv1OutW + 2 * kConv2Pad - kConv2K) / kConv2Stride + 1;  // 16

// ---- detection head: 2 -> 6 channels, 1x1, stride 1, pad 0, LINEAR --------
// Channels: [0]=class0(red) score, [1]=class1(blue) score,
//           [2..5] = tx,ty,tw,th box-regression (anchor-relative).
constexpr int kNumClasses  = 2;
constexpr int kHeadIn      = kConv2Out;
constexpr int kHeadOut     = kNumClasses + 4;   // = 6
constexpr int kHeadK       = 1;
constexpr int kHeadStride  = 1;
constexpr int kHeadPad     = 0;
constexpr int kHeadOutH    = kConv2OutH;        // 1x1 conv: spatial size unchanged
constexpr int kHeadOutW    = kConv2OutW;

// ---- detection grid (= head's spatial output; named separately because
//      the post-processing kernels reason about "cells", not "pixels") ----
constexpr int kGridH = kHeadOutH;               // 16
constexpr int kGridW = kHeadOutW;               // 16
static_assert(kGridH == kConv2OutH && kGridW == kConv2OutW,
             "grid size must equal the head's spatial output — see kernels.cuh SECTION 1");

// Cell size in NETWORK-INPUT pixels (4.0 = 64/16): the box-decode anchor
// arithmetic below places a cell's box center at (gx+0.5, gy+0.5)*kCellPx.
constexpr float kCellPx   = static_cast<float>(kNetW) / static_cast<float>(kGridW);
// Fixed anchor box side length, NETWORK-INPUT pixels. Chosen to equal the
// synthetic rectangles' resized size EXACTLY (source 15px * 0.8 = 12px) —
// see README "Limitations": the regression weights are zero, so every
// decoded box uses this anchor size unmodified; a trained head would learn
// a per-cell REFINEMENT on top of it via the same formula.
constexpr float kAnchorPx = 12.0f;

// ---- post-processing thresholds (tuned for the committed scene; the
//      margins are wide — see THEORY.md "How we verify correctness" for
//      the measured gap between background and object scores) -----------
constexpr float kScoreThreshold    = 0.7f;   // keep cells with score > this
constexpr float kNmsIouThreshold   = 0.25f;  // suppress same-class IoU > this
constexpr int   kKeypointWinRadius = 2;      // keypoint search window: (2R+1)^2 = 5x5 cells

// Exact upper bound on pre-NMS candidates: argmax_decode picks AT MOST one
// winning class per grid cell, so at most kGridH*kGridW cells can ever pass
// the threshold. This bound is used to size the compacted candidate buffer
// — no guesswork, no silent truncation risk.
constexpr int kMaxCandidates = kGridH * kGridW;   // 256

// ===========================================================================
// SECTION 2 — the Detection record: the shared "what did we find" struct
// produced by threshold_box_decode, consumed by NMS and keypoint_extract,
// and finally written to the demo artifacts (demo/out/detections.csv/.pgm).
// Plain-old-data on purpose: it crosses the host/device boundary via a flat
// cudaMemcpy and is written to disk field-by-field — no vtables, no STL.
// ===========================================================================
struct Detection {
    float score;      // winning class's confidence (post-argmax, PRE-threshold
                       // value retained for traceability — unitless)
    int   class_id;    // 0 = red, 1 = blue (kNumClasses-way; see conv1 doc above)
    int   cell_index;  // gy*kGridW + gx — the ORIGINATING grid cell. Kept
                       // explicitly (rather than re-derived from the box)
                       // because a REAL regression head can move the box
                       // center away from the cell center, at which point
                       // inverse-decoding the cell would be ambiguous —
                       // exactly the kind of bug this field prevents.
    float x0, y0, x1, y1; // decoded box corners, NETWORK-INPUT pixel space
                          // (float; valid range roughly [0,kNetW]x[0,kNetH],
                          // may extend slightly outside — not clamped, see
                          // kernels.cu box-decode comment)
    float kp_x, kp_y;     // keypoint location, NETWORK-INPUT pixel space
                          // (set by keypoint_extract; (-1,-1) beforehand —
                          // a sentinel documenting "not yet computed")
};

// ===========================================================================
// SECTION 3 — the weight blob: the "network's" learned (here: hand-fixed)
// parameters, loaded from data/sample/weights.bin by main.cu's strict
// loader and shared, read-only, by every stage of both the GPU and CPU
// paths — and by the optional TensorRT builder (tensorrt_path.cpp), which
// constructs an equivalent engine from the SAME numbers.
//
// FILE FORMAT (data/sample/weights.bin), byte-exact, little-endian:
//   bytes  0.. 7  : magic   = "RCWTPK01" (ASCII, NOT NUL-terminated)
//   bytes  8..11  : uint32  = format_version (currently 1)
//   bytes 12..    : float32 payload, IN THIS EXACT ORDER, no padding:
//       conv1_w[kConv1Out][kConv1In][kConv1K][kConv1K]   (2*3*3*3 = 54 floats)
//       conv1_b[kConv1Out]                                (2 floats)
//       conv2_w[kConv2Out][kConv2In][kConv2K][kConv2K]   (2*2*3*3 = 36 floats)
//       conv2_b[kConv2Out]                                (2 floats)
//       head_w [kHeadOut][kHeadIn][kHeadK][kHeadK]       (6*2*1*1 = 12 floats)
//       head_b [kHeadOut]                                 (6 floats)
//   Total: 112 floats = 448 bytes + 12-byte header = 460 bytes.
// The loader (main.cu: load_weight_blob) reads each array with its OWN
// ifstream::read() call, in this order — never one bulk struct-sized read
// — so the format never depends on the compiler's struct-packing rules
// (CLAUDE.md §12: byte-exact, documented, and actually enforced).
// scripts/make_synthetic.py is the single writer of this format; keep the
// two in lockstep if you ever change a layer's shape.
// ===========================================================================
struct WeightBlob {
    float conv1_w[kConv1Out][kConv1In][kConv1K][kConv1K];
    float conv1_b[kConv1Out];
    float conv2_w[kConv2Out][kConv2In][kConv2K][kConv2K];
    float conv2_b[kConv2Out];
    float head_w[kHeadOut][kHeadIn][kHeadK][kHeadK];
    float head_b[kHeadOut];
};

// ===========================================================================
// SECTION 4 — kernel & launcher declarations.
//
// Why the __CUDACC__ fence? reference_cpu.cpp is compiled by cl.exe (the
// HOST compiler), which does not understand __global__/__device__; nvcc
// defines __CUDACC__ only when IT is compiling. Fencing the device-only
// __global__ prototypes keeps this header includable from both compilers
// (the standard trick used throughout this repository — see 08.01/33.01).
// ===========================================================================
#ifdef __CUDACC__

// preprocess_kernel — HWC uint8 [kSrcH,kSrcW,3] -> CHW float32
// [3,kNetH,kNetW] via bilinear resize + per-channel normalize + transpose.
// Full documentation (thread mapping, resize math) sits with the
// definition in kernels.cu.
__global__ void preprocess_kernel(const uint8_t* __restrict__ src_hwc,
                                  float* __restrict__ net_chw);

// conv2d_kernel — GENERIC direct 2D convolution + optional ReLU. Reused,
// unchanged, for conv1, conv2, AND the 1x1 detection head (a 1x1 conv IS a
// per-cell linear layer — see kernels.cu). One thread per output element
// (co,oy,ox); each thread walks its own Cin*K*K receptive field.
__global__ void conv2d_kernel(const float* __restrict__ in,
                              const float* __restrict__ w,
                              const float* __restrict__ b,
                              float* __restrict__ out,
                              int Cin, int Cout, int Hin, int Win,
                              int K, int stride, int pad,
                              int Hout, int Wout,
                              bool relu);

// argmax_decode_kernel — one thread per grid cell: argmax over the
// kNumClasses score channels of head_out -> best_class[cell], best_score[cell].
__global__ void argmax_decode_kernel(const float* __restrict__ head_out,
                                     int* __restrict__ best_class,
                                     float* __restrict__ best_score);

// threshold_box_decode_kernel — one thread per grid cell: threshold +
// anchor-arithmetic box decode + GPU STREAM COMPACTION via atomicAdd on
// *count. Candidates buffer must hold kMaxCandidates Detection slots.
__global__ void threshold_box_decode_kernel(const int* __restrict__ best_class,
                                            const float* __restrict__ best_score,
                                            const float* __restrict__ head_out,
                                            Detection* __restrict__ candidates,
                                            int* __restrict__ count);

// iou_matrix_kernel — all-pairs IoU of n (sorted) candidate boxes. One
// thread per (i,j) pair; iou_out is a flattened n*n row-major matrix.
__global__ void iou_matrix_kernel(const Detection* __restrict__ boxes,
                                  int n,
                                  float* __restrict__ iou_out);

// keypoint_extract_kernel — one thread per surviving detection: local
// (2*kKeypointWinRadius+1)^2 window argmax over the winning class's score
// heatmap (head_out channel == detections[i].class_id), writing kp_x/kp_y.
__global__ void keypoint_extract_kernel(Detection* __restrict__ detections,
                                        int n,
                                        const float* __restrict__ head_out);

#endif // __CUDACC__ --------------------------------------------------------

// ---- host-callable launch wrappers (own grid/block math + error check) ---
// Declared OUTSIDE the __CUDACC__ fence: any translation unit may call
// them (only their DEFINITIONS, in kernels.cu, need nvcc). All pointers
// marked d_ are DEVICE pointers the caller allocated.
void launch_preprocess(const uint8_t* d_src_hwc, float* d_net_chw);

void launch_conv2d(const float* d_in, const float* d_w, const float* d_b,
                   float* d_out,
                   int Cin, int Cout, int Hin, int Win,
                   int K, int stride, int pad, int Hout, int Wout,
                   bool relu);

void launch_argmax_decode(const float* d_head_out, int* d_best_class, float* d_best_score);

// Zeroes *d_count internally before launching (documented so callers never
// forget the reset — a stream-compaction counter left dirty from a
// previous call is a classic silent-corruption bug).
void launch_threshold_box_decode(const int* d_best_class, const float* d_best_score,
                                 const float* d_head_out,
                                 Detection* d_candidates, int* d_count);

void launch_iou_matrix(const Detection* d_boxes_sorted, int n, float* d_iou_out);

void launch_keypoint_extract(Detection* d_detections, int n, const float* d_head_out);

// ===========================================================================
// SECTION 5 — CPU references (reference_cpu.cpp): an INDEPENDENT, plain
// C++ twin of every stage above (deliberate duplication, not shared code —
// CLAUDE.md §5/§9: a bug common to both paths must not be able to hide).
// ===========================================================================
void preprocess_cpu(const uint8_t* src_hwc, float* net_chw);

void conv2d_cpu(const float* in, const float* w, const float* b, float* out,
                int Cin, int Cout, int Hin, int Win,
                int K, int stride, int pad, int Hout, int Wout,
                bool relu);

void argmax_decode_cpu(const float* head_out, int* best_class, float* best_score);

// Sequential compaction via std::vector::push_back — the CPU's natural
// equivalent of the GPU kernel's atomicAdd-based compaction (kernels.cu
// documents the contrast explicitly).
void threshold_box_decode_cpu(const int* best_class, const float* best_score,
                              const float* head_out,
                              struct DetectionList* out_list);

// nms_cpu — sequential greedy NMS: sort-by-score (stable, tie-broken by
// cell_index — the SAME deterministic rule main.cu applies to the GPU
// path's candidates, so both paths agree even on exact score ties) then
// greedy IoU suppression. This function performs BOTH the "IoU matrix" and
// the "greedy scan" steps sequentially — the GPU path keeps them as two
// explicit phases (a real kernel + a host scan) precisely to show where
// the parallelism lives; here there is only one, honest, O(n^2) CPU loop.
void nms_cpu(struct DetectionList* candidates, float iou_threshold,
            struct DetectionList* out_kept);

void keypoint_extract_cpu(struct DetectionList* detections, const float* head_out);

// ---------------------------------------------------------------------------
// DetectionList — a tiny fixed-capacity array wrapper (kMaxCandidates slots
// is always enough — see the kMaxCandidates derivation above) used only by
// the CPU oracle, so reference_cpu.cpp stays free of <vector> churn at the
// hot call sites and both paths can be compared slot-for-slot after the
// SAME deterministic sort. Plain struct, no STL, matches this repo's
// "CPU reference stays dead simple" rule (CLAUDE.md §5).
// ---------------------------------------------------------------------------
struct DetectionList {
    Detection items[kMaxCandidates];
    int count = 0;
};

// ===========================================================================
// SECTION 6 — the optional TensorRT path (README "Build" documents the
// exact opt-in: define USE_TENSORRT and add the TensorRT include/lib
// paths). tensorrt_path_available() is ALWAYS declared/defined so main.cu
// can report the build's status uniformly; run_optional_tensorrt_demo() is
// only declared when USE_TENSORRT is actually defined, so the DEFAULT
// build never even NAMES a TensorRT type. See tensorrt_path.cpp for the
// full, documented, compile-ready-but-NOT-exercised-on-this-machine engine
// build + inference code.
// ===========================================================================
bool tensorrt_path_available();

#ifdef USE_TENSORRT
// Builds (or loads a cached) TensorRT engine from the SAME weights.bin,
// runs one inference on the SAME preprocessed tensor our CUDA kernels
// already produced, and hands the engine's output straight back into our
// UNCHANGED argmax/threshold/NMS/keypoint kernels — the point being that
// those four kernels do not know or care whether the 2 conv layers ran as
// hand-written __global__ launches or as one fused TensorRT engine.
void run_optional_tensorrt_demo(const char* weights_path, const float* d_net_chw);
#endif

#endif // PROJECT_KERNELS_CUH
