// ===========================================================================
// main.cu — entry point for project 29.05
//           Ultrasound: GPU beamforming (plane-wave delay-and-sum B-mode)
//
// EDUCATIONAL / SYNTHETIC ONLY (CLAUDE.md paragraph 1, 8, and the medical-
// robotics rule in paragraph 8): every scatterer this program images comes
// from a numerical phantom generated by scripts/make_synthetic.py — never
// patient data — and nothing this program prints or writes is a diagnostic
// or therapeutic claim. This project teaches ultrasound SIGNAL PROCESSING
// (beamforming), not medicine.
//
// What this program does, start to finish
// -----------------------------------------
//   1. Load the committed array/pulse/phantom-region parameters
//      (data/sample/array_params.csv, cross-checked against kernels.cuh —
//      the 03.01 pattern) and the point-scatterer phantom
//      (data/sample/phantom.csv: 9 wire targets + a high-scattering
//      inclusion + background speckle scatterers).
//   2. SYNTHESIZE the channel data: for every scatterer and every array
//      element, the exact two-way pulse-echo time-of-flight, a Gaussian-
//      windowed carrier pulse, 1/r receive-spreading falloff, and thermal
//      noise (host-only, deterministic — the project's SYNTHETIC SENSOR,
//      not the taught algorithm; see the header comment in kernels.cuh).
//   3. GPU PIPELINE (the taught algorithm, three stages):
//        das_kernel -> quadrature_demod_kernel -> envelope_lowpass_kernel
//        -> log_compress_kernel                      (kernels.cu)
//   4. CPU PIPELINE: das_cpu -> envelope_detect_cpu -> log_compress_cpu
//      (reference_cpu.cpp), on the IDENTICAL channel data.
//   5. VERIFY STAGE (the §5 GPU-vs-CPU gate, three sub-checks): the
//      beamformed RF image, the envelope, and the final dB image must each
//      agree between the two pipelines within a documented tolerance.
//   6. FOUR ANALYTIC / KNOWN-TRUTH gates (the physics made measurable):
//        (i)   LOCALIZATION — every wire target's image peak must land
//              within one resolution cell of its true position.
//        (ii)  RESOLUTION — the isolated center wire's measured -6 dB
//              lateral/axial point-spread-function width must match the
//              derived lambda*F# / (cycles*lambda/2) formulas within a
//              documented factor.
//        (iii) CONTRAST — the inclusion's mean dB must exceed the
//              background speckle's mean dB by a documented margin.
//        (iv)  DELAY_CHECK — the DAS delay formula, evaluated for one
//              known (pixel, element) pair, must equal an independently
//              re-derived closed-form two-way time within float tolerance.
//   7. Artifacts: demo/out/bmode.pgm (the B-mode image, wire peaks marked)
//      and demo/out/psf_profile.csv (the isolated wire's lateral/axial
//      dB profiles — the resolution measurement, plottable).
//
// Output contract (load-bearing!): stable lines are "[demo]", "PROBLEM:",
// "SCENARIO:", "VERIFY:", "LOCALIZATION:", "RESOLUTION:", "CONTRAST:",
// "DELAY_CHECK:", "ARTIFACT:", "RESULT:" — "[info]"/"[time]" are NOT diffed
// (device names and measured margins vary by machine/GPU architecture,
// same reasoning as 08.01/03.01). Change a stable line -> update
// demo/expected_output.txt in the same change.
//
// Read this first, then kernels.cuh -> kernels.cu -> reference_cpu.cpp.
// ===========================================================================

#include "kernels.cuh"
#include "util/cuda_check.cuh"
#include "util/timer.cuh"

#include <algorithm>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#ifdef _WIN32
#include <direct.h>               // _mkdir (std::filesystem avoided in .cu — 07.09/08.01 precedent)
#else
#include <sys/stat.h>
#endif

namespace {
constexpr float kPiF = 3.14159265358979323846f;

// ---------------------------------------------------------------------------
// Channel-data synthesis constants. These describe the SYNTHETIC SENSOR
// (how main.cu invents RF traces from the phantom), not the beamforming
// algorithm kernels.cuh/kernels.cu teach — so they live here, not there.
// ---------------------------------------------------------------------------
constexpr float    kAmpRefRangeM    = 0.020f;  // reference range for the 1/r receive-spreading
                                                // falloff (m) — an arbitrary teaching scale that
                                                // keeps raw channel amplitudes O(1) for mid-field
                                                // scatterers; NOT a calibrated acoustic-intensity
                                                // model (README/THEORY "Limitations").
constexpr float    kChannelNoiseStd = 0.015f;  // thermal-noise std-dev added to every raw channel
                                                // sample (unitless teaching scale, same idea as
                                                // 03.01's kNoiseStd on its complex baseband cube).
constexpr uint32_t  kNoiseSeed       = 42u;     // fixed seed: CLAUDE.md §12 determinism
constexpr float    kChannelWindowSigmas = 5.0f; // truncate each scatterer's pulse contribution at
                                                // +/-5 sigma of the Gaussian envelope (THEORY.md
                                                // "Numerical considerations" bounds the truncation
                                                // error: exp(-5^2/2) ~ 3.7e-6 of peak amplitude).

// Ground-truth verification constants (main.cu's four analytic gates).
constexpr float kWireSearchRadiusM   = 1.5e-3f;  // search window around each wire's TRUE position
                                                  // when hunting for its image peak — generous vs.
                                                  // the ~0.3-0.5mm resolution, well inside the 4mm
                                                  // gap to the nearest neighboring wire (no risk of
                                                  // locking onto the wrong target).
constexpr float kPsfSearchWindowM    = 4.0e-3f;  // half-width of the profile extracted around the
                                                  // isolated center wire for -6dB width measurement.
constexpr float kResolutionFactorLo  = 0.3f;     // measured/derived resolution ratio must fall in
constexpr float kResolutionFactorHi  = 3.0f;     // [Lo, Hi] — THEORY.md "How we verify correctness"
                                                  // explains why the first-order lambda*F# / pulse-
                                                  // length formulas are estimates, not exact
                                                  // predictions, and derives this factor's width.
constexpr float kContrastMinDb       = 2.0f;     // inclusion mean dB must exceed background mean dB
                                                  // by at least this much (measured margin printed
                                                  // on an [info] line; README/THEORY document the
                                                  // measured value this bound sits comfortably below).
constexpr float kDelayToleranceS     = 5.0e-9f;  // delay-formula sanity gate: float vs. independent
                                                  // double closed-form, tolerance far above float32
                                                  // rounding (~1e-12s at this magnitude) and far
                                                  // below one sample period (25 ns at fs=40MHz).

// Background sample region for the contrast gate: a rectangle chosen to
// avoid every wire target AND the inclusion disk (data/README.md documents
// the phantom geometry this assumes — cross-checked visually against
// data/sample/phantom.csv's wire/inclusion placement).
constexpr float kBgRectXLoM = 3.0e-3f, kBgRectXHiM = 8.0e-3f;
constexpr float kBgRectZLoM = 22.0e-3f, kBgRectZHiM = 28.0e-3f;
}  // namespace

// ===========================================================================
// Deterministic noise generator (03.01-style: xorshift32 + a 32-bit
// avalanche hash to decorrelate consecutive indices, then Box-Muller).
// Duplicated here rather than shared with kernels.cu because this program's
// noise is HOST-only (the channel-data synthesizer never runs on the GPU —
// see the file header) — there is nothing to keep byte-identical across a
// host/device boundary, unlike kernels.cu/reference_cpu.cpp's beamforming
// math, which DOES need that discipline.
// ---------------------------------------------------------------------------
static inline uint32_t xorshift32_step(uint32_t& state)
{
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
}

// Chris Wellons' "lowbias32" avalanche finalizer — see 03.01's kernels.cu
// for the full rationale (a linearly-incrementing seed fed straight into
// xorshift32 leaves detectable structure between neighboring indices; this
// mixes it away first).
static inline uint32_t hash32_mix(uint32_t x)
{
    x ^= x >> 16;
    x *= 0x7feb352dU;
    x ^= x >> 15;
    x *= 0x846ca68bU;
    x ^= x >> 16;
    return x;
}

static inline float uniform01_from(uint32_t& state)
{
    return (xorshift32_step(state) >> 8) * (1.0f / 16777216.0f) + (0.5f / 16777216.0f);
}

// ===========================================================================
// Path helpers (08.01/03.01 precedent): resolve data/demo paths relative to
// the running executable so the demo works from any CWD.
// ===========================================================================
static std::string project_root_from(const char* argv0)
{
    std::string exe(argv0 ? argv0 : "");
    size_t cut = exe.find_last_of("/\\");
    if (cut == std::string::npos) return ".";
    return exe.substr(0, cut) + "/../../..";
}

static std::string find_data_file(const std::string& filename, const char* argv0)
{
    std::vector<std::string> candidates = {
        project_root_from(argv0) + "/data/sample/" + filename,
        "data/sample/" + filename,
        "../data/sample/" + filename,
    };
    for (const auto& c : candidates)
        if (std::ifstream(c).is_open()) return c;
    return "";
}

static bool ensure_dir(const std::string& path)
{
#ifdef _WIN32
    const int r = _mkdir(path.c_str());
#else
    const int r = mkdir(path.c_str(), 0755);
#endif
    return r == 0 || errno == EEXIST;
}

// ===========================================================================
// Phantom loading — array_params.csv (cross-checked, 03.01-style) and
// phantom.csv (the scatterer list). See scripts/make_synthetic.py and
// data/README.md for the file formats.
// ===========================================================================

struct Scatterer {
    float x_m, z_m;   // position in the array/image frame (m) — kernels.cuh's layout
    float amp;         // relative reflectivity (unitless, teaching scale)
    int   kind;         // 0 = wire, 1 = inclusion, 2 = speckle
};

struct ArrayParamsFile {
    int    num_elements = 0;
    double pitch_m = 0, fc_hz = 0, fs_hz = 0, c_mps = 0, fnumber = 0;
    double incl_x_m = 0, incl_z_m = 0, incl_radius_m = 0;
    bool   loaded = false;
};

static ArrayParamsFile load_array_params(const std::string& path)
{
    ArrayParamsFile p;
    std::ifstream in(path);
    if (!in.is_open()) return p;

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::stringstream ss(line);
        std::string cell;
        std::vector<std::string> f;
        while (std::getline(ss, cell, ',')) f.push_back(cell);
        if (f.size() != 9) {
            std::fprintf(stderr, "array_params: expected 9 fields, got %zu\n", f.size());
            return ArrayParamsFile{};
        }
        p.num_elements = std::atoi(f[0].c_str());
        p.pitch_m      = std::strtod(f[1].c_str(), nullptr);
        p.fc_hz        = std::strtod(f[2].c_str(), nullptr);
        p.fs_hz        = std::strtod(f[3].c_str(), nullptr);
        p.c_mps        = std::strtod(f[4].c_str(), nullptr);
        p.fnumber      = std::strtod(f[5].c_str(), nullptr);
        p.incl_x_m     = std::strtod(f[6].c_str(), nullptr);
        p.incl_z_m     = std::strtod(f[7].c_str(), nullptr);
        p.incl_radius_m= std::strtod(f[8].c_str(), nullptr);
        p.loaded = true;
        break;   // one data row expected
    }
    return p;
}

// Returns "" if the file matches the build; otherwise a human-readable
// description of the first mismatch found (the 03.01 pattern: a drift
// between scripts/make_synthetic.py and kernels.cuh becomes a loud, early
// failure rather than a silently wrong demo).
static std::string check_array_params(const ArrayParamsFile& p)
{
    if (!p.loaded) return "file missing or malformed";
    char buf[256];
    if (p.num_elements != kNumElements) {
        std::snprintf(buf, sizeof(buf), "num_elements mismatch: file=%d build=%d", p.num_elements, kNumElements);
        return buf;
    }
    auto rel_mismatch = [](double file_v, double build_v, double tol_rel) {
        return std::fabs(file_v - build_v) > tol_rel * std::max(std::fabs(build_v), 1e-12);
    };
    if (rel_mismatch(p.pitch_m, kElementPitchM, 1e-5)) {
        std::snprintf(buf, sizeof(buf), "pitch_m mismatch: file=%.8f build=%.8f", p.pitch_m, static_cast<double>(kElementPitchM));
        return buf;
    }
    if (rel_mismatch(p.fc_hz, kCenterFreqHz, 1e-5)) {
        std::snprintf(buf, sizeof(buf), "fc_hz mismatch: file=%.1f build=%.1f", p.fc_hz, static_cast<double>(kCenterFreqHz));
        return buf;
    }
    if (rel_mismatch(p.fs_hz, kSamplingFreqHz, 1e-5)) {
        std::snprintf(buf, sizeof(buf), "fs_hz mismatch: file=%.1f build=%.1f", p.fs_hz, static_cast<double>(kSamplingFreqHz));
        return buf;
    }
    if (rel_mismatch(p.c_mps, kSoundSpeedMps, 1e-5)) {
        std::snprintf(buf, sizeof(buf), "c_mps mismatch: file=%.1f build=%.1f", p.c_mps, static_cast<double>(kSoundSpeedMps));
        return buf;
    }
    if (rel_mismatch(p.fnumber, kFNumber, 1e-4)) {
        std::snprintf(buf, sizeof(buf), "fnumber mismatch: file=%.3f build=%.3f", p.fnumber, static_cast<double>(kFNumber));
        return buf;
    }
    if (rel_mismatch(p.incl_x_m, kInclusionCenterXM, 1e-4)) {
        std::snprintf(buf, sizeof(buf), "incl_x_m mismatch: file=%.8f build=%.8f", p.incl_x_m, static_cast<double>(kInclusionCenterXM));
        return buf;
    }
    if (rel_mismatch(p.incl_z_m, kInclusionCenterZM, 1e-4)) {
        std::snprintf(buf, sizeof(buf), "incl_z_m mismatch: file=%.8f build=%.8f", p.incl_z_m, static_cast<double>(kInclusionCenterZM));
        return buf;
    }
    if (rel_mismatch(p.incl_radius_m, kInclusionRadiusM, 1e-4)) {
        std::snprintf(buf, sizeof(buf), "incl_radius_m mismatch: file=%.8f build=%.8f", p.incl_radius_m, static_cast<double>(kInclusionRadiusM));
        return buf;
    }
    return "";
}

// load_phantom — strict CSV loader for data/sample/phantom.csv, rows
// "kind,x_m,z_m,amp_rel" (the header row, if present, is skipped by its
// literal "kind" first field). Same strict-loader discipline as 08.01's
// scenario loader / 03.01's targets.csv: any malformed row aborts the demo.
static int load_phantom(const std::string& path, std::vector<Scatterer>& out)
{
    std::ifstream in(path);
    if (!in.is_open()) return -1;
    out.clear();

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::stringstream ss(line);
        std::string cell;
        std::vector<std::string> f;
        while (std::getline(ss, cell, ',')) f.push_back(cell);
        if (f.size() != 4) {
            std::fprintf(stderr, "phantom.csv: expected 4 fields, got %zu\n", f.size());
            return -1;
        }
        if (f[0] == "kind") continue;   // header row

        Scatterer sc{};
        if      (f[0] == "wire")      sc.kind = 0;
        else if (f[0] == "inclusion") sc.kind = 1;
        else if (f[0] == "speckle")   sc.kind = 2;
        else {
            std::fprintf(stderr, "phantom.csv: unknown kind '%s'\n", f[0].c_str());
            return -1;
        }
        sc.x_m = std::strtof(f[1].c_str(), nullptr);
        sc.z_m = std::strtof(f[2].c_str(), nullptr);
        sc.amp = std::strtof(f[3].c_str(), nullptr);
        out.push_back(sc);
    }
    return static_cast<int>(out.size());
}

// ===========================================================================
// Channel-data synthesis — the project's SYNTHETIC SENSOR (kernels.cuh's
// file header explains why this is data generation, not the taught
// algorithm, and therefore lives here rather than in kernels.cu/
// reference_cpu.cpp with a GPU/CPU verification gate of its own).
//
// Physics, one scatterer at a time (THEORY.md "The problem" derives every
// line): a scatterer at (xs, zs) with relative reflectivity `amp` returns a
// pulse to element e with total two-way delay
//     t(e) = zs/c + sqrt((xs-x_e)^2 + zs^2)/c          (identical formula
//                                                        to das_kernel's —
//                                                        the phantom sits
//                                                        exactly where the
//                                                        beamformer expects)
// scaled by a 1/r RECEIVE-spreading falloff (the plane-wave TRANSMIT does
// not spread; only the scattered spherical return wave does — THEORY.md
// derives why), and shaped by the Gaussian-windowed carrier pulse
//     p(dt) = exp(-dt^2 / (2*sigma^2)) * cos(2*pi*fc*dt)
// evaluated at dt = t_sample - t(e) for every channel sample within
// kChannelWindowSigmas of the arrival (an O(1)-per-scatterer windowed
// accumulate, not an O(kNumSamples) sweep — THEORY.md "The GPU mapping"
// notes this is the same "only touch what matters" idea das_kernel's
// f-number apodization applies to the ELEMENT axis, here applied to the
// TIME axis instead). Every scatterer contributes to every element
// independently and the contributions SUM — the coherent superposition
// that, for the many equal-amplitude, randomly-positioned background
// scatterers, IS the speckle pattern (THEORY.md "The problem": speckle is
// interference, not noise, and this function is the proof-by-construction).
// Finally, independent thermal noise is added per (element, sample).
// ---------------------------------------------------------------------------
static void simulate_channel_data(const std::vector<Scatterer>& phantom, std::vector<float>& channel)
{
    channel.assign(static_cast<size_t>(kNumElements) * kNumSamples, 0.0f);

    const float sigma_samples = kPulseSigmaS * kSamplingFreqHz;    // Gaussian envelope width, in samples
    const int window_radius = static_cast<int>(std::ceil(kChannelWindowSigmas * sigma_samples));

    for (const Scatterer& sc : phantom) {
        for (int e = 0; e < kNumElements; ++e) {
            // Element geometry — the SAME one-line formula das_kernel/das_cpu
            // use (kernels.cuh's documented-duplication note); the phantom's
            // scatterers are placed in that exact array/image frame.
            const float x_e = (static_cast<float>(e) - 0.5f * (kNumElements - 1)) * kElementPitchM;

            const float dx = sc.x_m - x_e;
            const float r_rx = std::sqrt(dx * dx + sc.z_m * sc.z_m);
            const float t_tx = sc.z_m / kSoundSpeedMps;
            const float t_total = t_tx + r_rx / kSoundSpeedMps;

            // 1/r receive-spreading falloff, referenced to kAmpRefRangeM so
            // raw amplitudes stay a teaching-friendly O(1) (see the constant's
            // doc comment above — not a calibrated intensity model).
            const float amp = sc.amp * (kAmpRefRangeM / std::max(r_rx, 1.0e-4f));

            const float center_sample = t_total * kSamplingFreqHz;
            const int   center_i = static_cast<int>(std::lround(static_cast<double>(center_sample)));

            for (int w = -window_radius; w <= window_radius; ++w) {
                const int s_idx = center_i + w;
                if (s_idx < 0 || s_idx >= kNumSamples) continue;

                const float t_sample = static_cast<float>(s_idx) / kSamplingFreqHz;
                const float dt = t_sample - t_total;    // signed time offset from the exact arrival
                const float envelope = std::exp(-(dt * dt) / (2.0f * kPulseSigmaS * kPulseSigmaS));
                const float carrier  = std::cos(2.0f * kPiF * kCenterFreqHz * dt);

                channel[static_cast<size_t>(e) * kNumSamples + s_idx] += amp * envelope * carrier;
            }
        }
    }

    // Thermal noise: independent N(0, kChannelNoiseStd^2) per (e, s), fully
    // deterministic from kNoiseSeed (CLAUDE.md §12) — same hash-then-
    // xorshift-then-Box-Muller construction 03.01 uses for its cube noise.
    for (size_t i = 0; i < channel.size(); ++i) {
        uint32_t state = hash32_mix(kNoiseSeed + static_cast<uint32_t>(i) * 2654435761u);
        const float u1 = uniform01_from(state);
        const float u2 = uniform01_from(state);
        const float r  = std::sqrt(-2.0f * std::log(u1));
        const float z  = r * std::cos(2.0f * kPiF * u2);
        channel[i] += kChannelNoiseStd * z;
    }
}

// ===========================================================================
// Ground-truth verification helpers.
// ===========================================================================

// host_env_max — small scalar reduction, deliberately kept on the host
// (206k floats, microseconds either way) — the same "small enough, keep it
// simple" call 08.01 makes for its softmin blend.
static float host_max(const std::vector<float>& v)
{
    float m = -1e30f;
    for (float x : v) if (x > m) m = x;
    return m;
}

struct WireResult {
    float true_x_m = 0, true_z_m = 0;
    int   ix_peak = -1, iz_peak = -1;
    float found_x_m = 0, found_z_m = 0;
    float err_m = 0;
    bool  found = false;
};

// localize_wire — search a small pixel window centered on a wire's TRUE
// position for the brightest (max dB) pixel, the honest "did the image
// actually put the target where physics says it should be" check.
static WireResult localize_wire(const std::vector<float>& db, float true_x, float true_z)
{
    WireResult r;
    r.true_x_m = true_x;
    r.true_z_m = true_z;

    const int ix_c = static_cast<int>(std::lround((true_x - kImageXMinM) / kImageDxM));
    const int iz_c = static_cast<int>(std::lround((true_z - kImageZMinM) / kImageDzM));
    const int rx = static_cast<int>(std::ceil(kWireSearchRadiusM / kImageDxM));
    const int rz = static_cast<int>(std::ceil(kWireSearchRadiusM / kImageDzM));

    float best = -1e30f;
    for (int iz = std::max(0, iz_c - rz); iz <= std::min(kImageNz - 1, iz_c + rz); ++iz) {
        for (int ix = std::max(0, ix_c - rx); ix <= std::min(kImageNx - 1, ix_c + rx); ++ix) {
            const float v = db[static_cast<size_t>(iz) * kImageNx + ix];
            if (v > best) { best = v; r.iz_peak = iz; r.ix_peak = ix; }
        }
    }
    if (r.ix_peak < 0) return r;

    r.found_x_m = kImageXMinM + static_cast<float>(r.ix_peak) * kImageDxM;
    r.found_z_m = kImageZMinM + static_cast<float>(r.iz_peak) * kImageDzM;
    const float ex = r.found_x_m - true_x, ez = r.found_z_m - true_z;
    r.err_m = std::sqrt(ex * ex + ez * ez);
    r.found = true;
    return r;
}

// find_mainlobe_edge — walk outward from a profile's peak index in
// `direction` (+1 or -1) until the value first drops below `threshold_db`,
// then linearly interpolate the sub-pixel crossing position. This is the
// standard "-6 dB mainlobe width" definition: the FIRST crossing outward
// from the peak, robust to sidelobes further out.
static bool find_mainlobe_edge(const std::vector<float>& db, const std::vector<float>& pos,
                               int peak_idx, float threshold_db, int direction, float& crossing_pos)
{
    const int n = static_cast<int>(db.size());
    int i = peak_idx;
    while (true) {
        const int j = i + direction;
        if (j < 0 || j >= n) return false;   // ran off the profile without crossing
        if (db[j] < threshold_db) {
            const float t = (threshold_db - db[i]) / (db[j] - db[i]);   // db[i]>=thr>db[j]
            crossing_pos = pos[i] + t * (pos[j] - pos[i]);
            return true;
        }
        i = j;
    }
}

// ===========================================================================
// Artifacts.
// ===========================================================================

// write_bmode_pgm — a binary PGM (P5) of the log-compressed B-mode image:
// rows = depth (shallow at top, matching a conventional on-screen B-mode
// display), columns = lateral position. Wire-target peaks are marked with
// a small bright crosshair (03.01's detection-marking idiom).
static bool write_bmode_pgm(const std::string& path, const std::vector<float>& db,
                            const std::vector<WireResult>& wires)
{
    std::vector<unsigned char> pixels(db.size());
    for (size_t i = 0; i < db.size(); ++i) {
        float norm = (db[i] + kDynamicRangeDb) / kDynamicRangeDb;   // 0 (floor) .. 1 (peak)
        norm = std::min(1.0f, std::max(0.0f, norm));
        pixels[i] = static_cast<unsigned char>(norm * 255.0f + 0.5f);
    }
    for (const WireResult& w : wires) {
        if (!w.found) continue;
        for (int k = -3; k <= 3; ++k) {
            const int ci = w.ix_peak + k;
            if (ci >= 0 && ci < kImageNx) pixels[static_cast<size_t>(w.iz_peak) * kImageNx + ci] = 255;
            const int ri = w.iz_peak + k;
            if (ri >= 0 && ri < kImageNz) pixels[static_cast<size_t>(ri) * kImageNx + w.ix_peak] = 255;
        }
    }

    std::ofstream f(path, std::ios::binary);
    if (!f.is_open()) return false;
    f << "P5\n" << kImageNx << ' ' << kImageNz << "\n255\n";
    f.write(reinterpret_cast<const char*>(pixels.data()), static_cast<std::streamsize>(pixels.size()));
    return f.good();
}

// write_psf_profile_csv — the isolated center wire's lateral and axial dB
// profiles, in one file (an "axis" column distinguishes the two runs) —
// the plottable evidence behind the RESOLUTION gate.
static bool write_psf_profile_csv(const std::string& path,
                                  const std::vector<float>& lateral_pos_mm, const std::vector<float>& lateral_db,
                                  const std::vector<float>& axial_pos_mm, const std::vector<float>& axial_db)
{
    std::ofstream f(path);
    if (!f.is_open()) return false;
    f << "axis,position_mm,db_relative\n";
    for (size_t i = 0; i < lateral_pos_mm.size(); ++i)
        f << "lateral," << lateral_pos_mm[i] << ',' << lateral_db[i] << '\n';
    for (size_t i = 0; i < axial_pos_mm.size(); ++i)
        f << "axial," << axial_pos_mm[i] << ',' << axial_db[i] << '\n';
    return f.good();
}

// ===========================================================================
// main
// ===========================================================================
int main(int argc, char** argv)
{
    std::string array_params_override, phantom_override;
    for (int i = 1; i < argc; ++i) {
        if      (!std::strcmp(argv[i], "--array-params") && i + 1 < argc) array_params_override = argv[++i];
        else if (!std::strcmp(argv[i], "--phantom")      && i + 1 < argc) phantom_override = argv[++i];
        else {
            std::fprintf(stderr, "usage: %s [--array-params array_params.csv] [--phantom phantom.csv]\n", argv[0]);
            return 2;
        }
    }

    std::printf("[demo] Ultrasound: GPU delay-and-sum B-mode beamforming (project 29.05, EDUCATIONAL/SYNTHETIC)\n");
    print_device_info();

    std::printf("PROBLEM: %d-element array, pitch %.2fmm, fc=%.1fMHz, fs=%.1fMHz, plane-wave TX, "
                "image %dx%d px over %.1fx%.1fmm (x,z), f-number %.1f, FP32\n",
                kNumElements, static_cast<double>(kElementPitchM) * 1000.0,
                static_cast<double>(kCenterFreqHz) / 1e6, static_cast<double>(kSamplingFreqHz) / 1e6,
                kImageNx, kImageNz,
                static_cast<double>(kImageXMaxM - kImageXMinM) * 1000.0,
                static_cast<double>(kImageZMaxM - kImageZMinM) * 1000.0,
                static_cast<double>(kFNumber));
    std::printf("[info] derived resolution (first-order estimate, THEORY.md derives both): "
                "lateral ~%.3fmm (lambda*F#), axial ~%.3fmm (cycles*lambda/2)\n",
                static_cast<double>(kLateralResM) * 1000.0, static_cast<double>(kAxialResM) * 1000.0);

    // ---- load & cross-check the committed array/pulse/phantom-region params ----
    const std::string params_path = array_params_override.empty()
        ? find_data_file("array_params.csv", argv[0]) : array_params_override;
    const std::string phantom_path = phantom_override.empty()
        ? find_data_file("phantom.csv", argv[0]) : phantom_override;

    if (params_path.empty() || phantom_path.empty()) {
        std::printf("SCENARIO: NOT FOUND - data/sample/{array_params,phantom}.csv missing (run scripts/make_synthetic.py?)\n");
        std::printf("RESULT: FAIL (scenario missing)\n");
        return 1;
    }
    const ArrayParamsFile ap = load_array_params(params_path);
    const std::string mismatch = check_array_params(ap);
    if (!mismatch.empty()) {
        std::printf("SCENARIO: MISMATCH - %s\n", mismatch.c_str());
        std::printf("RESULT: FAIL (array_params.csv does not match this build's kernels.cuh constants)\n");
        return 1;
    }

    std::vector<Scatterer> phantom;
    const int n_scatterers = load_phantom(phantom_path, phantom);
    if (n_scatterers <= 0) {
        std::printf("SCENARIO: MALFORMED - see stderr\n");
        std::printf("RESULT: FAIL (phantom.csv malformed or empty)\n");
        return 1;
    }
    int n_wire = 0, n_incl = 0, n_spk = 0;
    std::vector<Scatterer> wires;
    for (const Scatterer& sc : phantom) {
        if (sc.kind == 0) { n_wire++; wires.push_back(sc); }
        else if (sc.kind == 1) n_incl++;
        else n_spk++;
    }
    std::printf("SCENARIO: %d scatterers loaded (%d wire, %d inclusion, %d speckle) from data/sample/phantom.csv [synthetic, seed %u]\n",
                n_scatterers, n_wire, n_incl, n_spk, kNoiseSeed);

    // ===================== Channel-data synthesis (host) ======================
    CpuTimer synth_timer;
    synth_timer.begin();
    std::vector<float> channel;
    simulate_channel_data(phantom, channel);
    const double synth_ms = synth_timer.end_ms();
    std::printf("[time] channel-data synthesis (host, %d scatterers x %d elements): %.1f ms\n",
                n_scatterers, kNumElements, synth_ms);

    // ===================== GPU PIPELINE (the taught algorithm) ================
    const size_t channel_count = static_cast<size_t>(kNumElements) * kNumSamples;
    const size_t image_count = static_cast<size_t>(kImageNz) * kImageNx;

    float *d_channel = nullptr, *d_rf = nullptr, *d_i = nullptr, *d_q = nullptr, *d_env = nullptr, *d_db = nullptr;
    CUDA_CHECK(cudaMalloc(&d_channel, channel_count * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_rf, image_count * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_i, image_count * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_q, image_count * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_env, image_count * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_db, image_count * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_channel, channel.data(), channel_count * sizeof(float), cudaMemcpyHostToDevice));

    std::vector<float> gpu_env(image_count);   // downloaded early: env_max is a host scalar (see kernels.cuh)

    GpuTimer gpu_timer;
    gpu_timer.begin();
    launch_das(d_channel, d_rf);
    launch_quadrature_demod(d_rf, d_i, d_q);
    launch_envelope_lowpass(d_i, d_q, d_env);
    CUDA_CHECK(cudaMemcpy(gpu_env.data(), d_env, image_count * sizeof(float), cudaMemcpyDeviceToHost));
    const float gpu_env_max = host_max(gpu_env);
    launch_log_compress(d_env, gpu_env_max, d_db);
    const float gpu_pipeline_ms = gpu_timer.end_ms();

    std::vector<float> gpu_rf(image_count), gpu_db(image_count);
    CUDA_CHECK(cudaMemcpy(gpu_rf.data(), d_rf, image_count * sizeof(float), cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(gpu_db.data(), d_db, image_count * sizeof(float), cudaMemcpyDeviceToHost));
    std::printf("[time] GPU pipeline (DAS -> quadrature demod -> envelope low-pass -> log compress): %.3f ms\n",
                static_cast<double>(gpu_pipeline_ms));

    CUDA_CHECK(cudaFree(d_channel));
    CUDA_CHECK(cudaFree(d_rf));
    CUDA_CHECK(cudaFree(d_i));
    CUDA_CHECK(cudaFree(d_q));
    CUDA_CHECK(cudaFree(d_env));
    CUDA_CHECK(cudaFree(d_db));

    // ===================== CPU PIPELINE (the oracle) ==========================
    std::vector<float> cpu_rf(image_count), cpu_env(image_count), cpu_db(image_count);
    CpuTimer cpu_timer;
    cpu_timer.begin();
    das_cpu(channel.data(), cpu_rf.data());
    envelope_detect_cpu(cpu_rf.data(), cpu_env.data());
    const float cpu_env_max = host_max(cpu_env);
    log_compress_cpu(cpu_env.data(), cpu_env_max, cpu_db.data());
    const double cpu_ms = cpu_timer.end_ms();
    std::printf("[time] CPU reference pipeline (das_cpu -> envelope_detect_cpu -> log_compress_cpu): %.1f ms | "
                "GPU speed-up (teaching artifact): %.0fx\n",
                cpu_ms, cpu_ms / (static_cast<double>(gpu_pipeline_ms) > 0.0 ? static_cast<double>(gpu_pipeline_ms) : 1.0));

    // ===================== VERIFY: three-stage GPU-vs-CPU gate =================
    // Each stage compared independently (a bug that partially cancels across
    // stages would slip past a single end-to-end check — kernels.cuh's file
    // header makes this argument explicitly).
    //
    // ABSOLUTE tolerances at all three stages, not relative-with-a-floor:
    // the RF image OSCILLATES through zero (it is a carrier-frequency
    // signal) and the envelope is a Rayleigh-distributed magnitude that
    // genuinely visits near-zero values at destructive-interference speckle
    // nulls (THEORY.md "The problem" — this is the same physics that makes
    // speckle speckle). A relative-with-floor comparison is the WRONG tool
    // exactly at those points: dividing a tiny-but-real FP32 rounding
    // difference by an arbitrary small floor manufactures a large relative
    // number that says nothing about correctness — an early version of this
    // gate did exactly that and reported a spurious worst-case relative
    // deviation of 5%, traced to a single near-null pixel with a genuinely
    // tiny absolute difference (THEORY.md "Numerical considerations" tells
    // the full story). The ABSOLUTE deviation, in contrast, stays small and
    // stable everywhere in the image (measured worst case on this machine:
    // RF ~1e-3 against a peak magnitude of ~10; envelope ~3e-4 against a
    // peak of ~6) — exactly the quantity these tolerances gate, with
    // generous headroom, the same "wide margin so ULP differences cannot
    // flip the verdict" philosophy 08.01 uses.
    float worst_abs_rf = 0.0f, worst_abs_env = 0.0f, worst_abs_db = 0.0f;
    for (size_t i = 0; i < image_count; ++i) {
        worst_abs_rf = std::max(worst_abs_rf, std::fabs(gpu_rf[i] - cpu_rf[i]));
        worst_abs_env = std::max(worst_abs_env, std::fabs(gpu_env[i] - cpu_env[i]));
        worst_abs_db = std::max(worst_abs_db, std::fabs(gpu_db[i] - cpu_db[i]));
    }
    constexpr float kTolAbsRf = 0.01f, kTolAbsEnv = 0.005f, kTolAbsDb = 0.05f;
    const bool verify_rf = worst_abs_rf <= kTolAbsRf;
    const bool verify_env = worst_abs_env <= kTolAbsEnv;
    const bool verify_db = worst_abs_db <= kTolAbsDb;
    const bool verify_pass = verify_rf && verify_env && verify_db;
    std::printf("[info] VERIFY stage 1/3 (DAS, RF image): worst absolute deviation %.5f (tol %.3f) -> %s\n",
                static_cast<double>(worst_abs_rf), static_cast<double>(kTolAbsRf), verify_rf ? "PASS" : "FAIL");
    std::printf("[info] VERIFY stage 2/3 (envelope): worst absolute deviation %.5f (tol %.3f) -> %s\n",
                static_cast<double>(worst_abs_env), static_cast<double>(kTolAbsEnv), verify_env ? "PASS" : "FAIL");
    std::printf("[info] VERIFY stage 3/3 (log compress): worst absolute deviation %.4f dB (tol %.2f dB) -> %s\n",
                static_cast<double>(worst_abs_db), static_cast<double>(kTolAbsDb), verify_db ? "PASS" : "FAIL");
    std::printf("VERIFY: %s (GPU matches CPU reference at all three beamforming stages within tolerance)\n",
                verify_pass ? "PASS" : "FAIL");

    // ===================== LOCALIZATION gate (i) ================================
    std::vector<WireResult> wire_results;
    const float localization_tol_m = std::max(kLateralResM, kAxialResM);   // "within one resolution cell"
    bool all_wires_ok = true;
    for (const Scatterer& w : wires) {
        WireResult r = localize_wire(gpu_db, w.x_m, w.z_m);
        wire_results.push_back(r);
        const bool ok = r.found && (r.err_m <= localization_tol_m);
        all_wires_ok = all_wires_ok && ok;
        const int true_ix = static_cast<int>(std::lround((w.x_m - kImageXMinM) / kImageDxM));
        const int true_iz = static_cast<int>(std::lround((w.z_m - kImageZMinM) / kImageDzM));
        const float db_true = gpu_db[static_cast<size_t>(true_iz) * kImageNx + true_ix];
        const float db_peak = gpu_db[static_cast<size_t>(r.iz_peak) * kImageNx + r.ix_peak];
        std::printf("[info]   wire true(x=%+.2fmm z=%.2fmm) db_true=%.2f -> peak(x=%+.2fmm z=%.2fmm) db_peak=%.2f err=%.3fmm (tol %.3fmm) %s\n",
                    static_cast<double>(w.x_m) * 1000.0, static_cast<double>(w.z_m) * 1000.0, static_cast<double>(db_true),
                    static_cast<double>(r.found_x_m) * 1000.0, static_cast<double>(r.found_z_m) * 1000.0, static_cast<double>(db_peak),
                    static_cast<double>(r.err_m) * 1000.0, static_cast<double>(localization_tol_m) * 1000.0,
                    ok ? "ok" : "FAIL");
    }
    std::printf("LOCALIZATION: %s (every wire target's image peak within one resolution cell of its true position)\n",
                all_wires_ok ? "PASS" : "FAIL");

    // ===================== RESOLUTION gate (ii) ==================================
    // The isolated center wire (0, 20mm) — nearest neighbor 4mm away in
    // every direction, far beyond the resolution — is data/README.md's
    // documented choice for the point-spread-function measurement.
    int center_idx = -1;
    for (size_t i = 0; i < wires.size(); ++i) {
        if (std::fabs(wires[i].x_m) < 1e-6f && std::fabs(wires[i].z_m - 0.020f) < 1e-6f) { center_idx = static_cast<int>(i); break; }
    }
    bool resolution_pass = false;
    float lateral_width_mm = 0.0f, axial_width_mm = 0.0f;
    std::vector<float> lat_pos_mm, lat_db, ax_pos_mm, ax_db;
    if (center_idx >= 0) {
        const WireResult& cw = wire_results[static_cast<size_t>(center_idx)];
        const int win_x = static_cast<int>(std::ceil(kPsfSearchWindowM / kImageDxM));
        const int win_z = static_cast<int>(std::ceil(kPsfSearchWindowM / kImageDzM));

        // Lateral profile: fixed depth row iz_peak, sweep ix.
        for (int ix = std::max(0, cw.ix_peak - win_x); ix <= std::min(kImageNx - 1, cw.ix_peak + win_x); ++ix) {
            lat_pos_mm.push_back((kImageXMinM + static_cast<float>(ix) * kImageDxM) * 1000.0f);
            lat_db.push_back(gpu_db[static_cast<size_t>(cw.iz_peak) * kImageNx + ix]);
        }
        // Axial profile: fixed lateral column ix_peak, sweep iz.
        for (int iz = std::max(0, cw.iz_peak - win_z); iz <= std::min(kImageNz - 1, cw.iz_peak + win_z); ++iz) {
            ax_pos_mm.push_back((kImageZMinM + static_cast<float>(iz) * kImageDzM) * 1000.0f);
            ax_db.push_back(gpu_db[static_cast<size_t>(iz) * kImageNx + cw.ix_peak]);
        }

        const int lat_peak_i = cw.ix_peak - std::max(0, cw.ix_peak - win_x);
        const int ax_peak_i  = cw.iz_peak - std::max(0, cw.iz_peak - win_z);
        const float peak_db_lat = lat_db[static_cast<size_t>(lat_peak_i)];
        const float peak_db_ax  = ax_db[static_cast<size_t>(ax_peak_i)];

        float lat_left, lat_right, ax_left, ax_right;
        const bool lat_ok = find_mainlobe_edge(lat_db, lat_pos_mm, lat_peak_i, peak_db_lat - 6.0f, -1, lat_left)
                          && find_mainlobe_edge(lat_db, lat_pos_mm, lat_peak_i, peak_db_lat - 6.0f, +1, lat_right);
        const bool ax_ok = find_mainlobe_edge(ax_db, ax_pos_mm, ax_peak_i, peak_db_ax - 6.0f, -1, ax_left)
                         && find_mainlobe_edge(ax_db, ax_pos_mm, ax_peak_i, peak_db_ax - 6.0f, +1, ax_right);
        if (lat_ok && ax_ok) {
            lateral_width_mm = lat_right - lat_left;
            axial_width_mm = ax_right - ax_left;
            const float derived_lateral_mm = kLateralResM * 1000.0f;   // kLateralResM, kAxialResM are always
            const float derived_axial_mm = kAxialResM * 1000.0f;       // strictly positive (lambda*F#, cycles*lambda/2)
            const float lat_ratio = lateral_width_mm / derived_lateral_mm;
            const float ax_ratio = axial_width_mm / derived_axial_mm;
            const bool lat_pass = lat_ratio >= kResolutionFactorLo && lat_ratio <= kResolutionFactorHi;
            const bool ax_pass = ax_ratio >= kResolutionFactorLo && ax_ratio <= kResolutionFactorHi;
            resolution_pass = lat_pass && ax_pass;
            std::printf("[info] RESOLUTION measured (isolated center wire, -6dB width): lateral %.3fmm (derived %.3fmm, ratio %.2fx) %s | "
                        "axial %.3fmm (derived %.3fmm, ratio %.2fx) %s\n",
                        static_cast<double>(lateral_width_mm), static_cast<double>(kLateralResM) * 1000.0, static_cast<double>(lat_ratio), lat_pass ? "ok" : "FAIL",
                        static_cast<double>(axial_width_mm), static_cast<double>(kAxialResM) * 1000.0, static_cast<double>(ax_ratio), ax_pass ? "ok" : "FAIL");
        } else {
            std::printf("[info] RESOLUTION: could not find a -6dB crossing within the search window\n");
        }
    } else {
        std::printf("[info] RESOLUTION: center wire (0, 20mm) not found in the loaded phantom\n");
    }
    std::printf("RESOLUTION: %s (measured -6dB PSF width matches the derived lambda*F# / cycles*lambda/2 formulas within a %.1fx-%.1fx factor)\n",
                resolution_pass ? "PASS" : "FAIL", static_cast<double>(kResolutionFactorLo), static_cast<double>(kResolutionFactorHi));

    // ===================== CONTRAST gate (iii) ===================================
    double sum_incl = 0.0, sum_bg = 0.0;
    long n_incl_px = 0, n_bg_px = 0;
    for (int iz = 0; iz < kImageNz; ++iz) {
        const float z = kImageZMinM + static_cast<float>(iz) * kImageDzM;
        for (int ix = 0; ix < kImageNx; ++ix) {
            const float x = kImageXMinM + static_cast<float>(ix) * kImageDxM;
            const float dxI = x - kInclusionCenterXM, dzI = z - kInclusionCenterZM;
            const size_t idx = static_cast<size_t>(iz) * kImageNx + ix;
            if (dxI * dxI + dzI * dzI <= kInclusionRadiusM * kInclusionRadiusM) {
                sum_incl += gpu_db[idx]; n_incl_px++;
            } else if (x >= kBgRectXLoM && x <= kBgRectXHiM && z >= kBgRectZLoM && z <= kBgRectZHiM) {
                sum_bg += gpu_db[idx]; n_bg_px++;
            }
        }
    }
    const float mean_incl_db = (n_incl_px > 0) ? static_cast<float>(sum_incl / n_incl_px) : -1e30f;
    const float mean_bg_db = (n_bg_px > 0) ? static_cast<float>(sum_bg / n_bg_px) : 1e30f;
    const float contrast_db = mean_incl_db - mean_bg_db;
    const bool contrast_pass = (n_incl_px > 0) && (n_bg_px > 0) && (contrast_db >= kContrastMinDb);
    std::printf("[info] CONTRAST measured: inclusion mean %.2fdB (%ld px) vs background mean %.2fdB (%ld px), margin %.2fdB (min %.2fdB)\n",
                static_cast<double>(mean_incl_db), n_incl_px, static_cast<double>(mean_bg_db), n_bg_px,
                static_cast<double>(contrast_db), static_cast<double>(kContrastMinDb));
    std::printf("CONTRAST: %s (the high-scattering inclusion's mean dB exceeds background speckle by the documented margin)\n",
                contrast_pass ? "PASS" : "FAIL");

    // ===================== DELAY_CHECK gate (iv) =================================
    // The DAS delay formula, evaluated in float for one known (pixel,
    // element) pair, vs. an INDEPENDENTLY re-derived double-precision
    // closed-form two-way time — a pure formula sanity check, isolated
    // from the rest of the pipeline (kernels.cuh's file header explains
    // why this is a genuine, non-circular test).
    const float z_test = 0.020f, x_test = 0.0f;
    const float x_e0 = (0.0f - 0.5f * (kNumElements - 1)) * kElementPitchM;   // element 0's position
    const float t_tx_f = z_test / kSoundSpeedMps;
    const float dx_f = x_e0 - x_test;
    const float r_rx_f = std::sqrt(dx_f * dx_f + z_test * z_test);
    const float t_formula = t_tx_f + r_rx_f / kSoundSpeedMps;

    const double z_d = 0.020, x_e0_d = static_cast<double>(x_e0), c_d = static_cast<double>(kSoundSpeedMps);
    const double t_tx_d = z_d / c_d;
    const double r_rx_d = std::sqrt(x_e0_d * x_e0_d + z_d * z_d);
    const double t_closed = t_tx_d + r_rx_d / c_d;

    const double delay_diff_s = std::fabs(static_cast<double>(t_formula) - t_closed);
    const bool delay_pass = delay_diff_s < static_cast<double>(kDelayToleranceS);
    std::printf("[info] DELAY_CHECK: pixel(x=0,z=20mm) element 0 -> formula %.6fus, closed-form %.6fus, diff %.3ens (tol %.1fns)\n",
                static_cast<double>(t_formula) * 1e6, t_closed * 1e6, delay_diff_s * 1e9, static_cast<double>(kDelayToleranceS) * 1e9);
    std::printf("DELAY_CHECK: %s (DAS two-way delay formula matches an independently re-derived closed-form value)\n",
                delay_pass ? "PASS" : "FAIL");

    // ===================== Artifacts ==============================================
    const std::string out_dir = project_root_from(argv[0]) + "/demo/out";
    bool artifact_ok = ensure_dir(out_dir);
    if (artifact_ok) artifact_ok = write_bmode_pgm(out_dir + "/bmode.pgm", gpu_db, wire_results);
    if (artifact_ok) artifact_ok = write_psf_profile_csv(out_dir + "/psf_profile.csv", lat_pos_mm, lat_db, ax_pos_mm, ax_db);
    if (artifact_ok)
        std::printf("ARTIFACT: wrote demo/out/bmode.pgm and demo/out/psf_profile.csv\n");
    else
        std::printf("ARTIFACT: FAILED to write demo/out/ files\n");

    // ===================== RESULT ===================================================
    const bool overall_pass = verify_pass && all_wires_ok && resolution_pass && contrast_pass && delay_pass && artifact_ok;
    if (overall_pass) {
        std::printf("RESULT: PASS (GPU matches CPU reference at every stage; wire localization, resolution, contrast, "
                    "and delay-formula gates all pass)\n");
        return EXIT_SUCCESS;
    } else {
        std::printf("RESULT: FAIL (see VERIFY/LOCALIZATION/RESOLUTION/CONTRAST/DELAY_CHECK lines above)\n");
        return EXIT_FAILURE;
    }
}
