#!/usr/bin/env python3
"""make_synthetic.py -- synthetic sample-data generator for project 21.04
(Speed-and-separation monitoring: depth streams -> minimum-distance fields
at frame rate, an ISO/TS 15066-style helper -- DIDACTIC, NOT a certified
safety function; see ../src/kernels.cuh for the full caveat).

Why this script exists (CLAUDE.md paragraph 8: synthetic-first)
-----------------------------------------------------------------
Every quantity this project consumes -- the human's walk, the robot's
reach cycle, the depth camera's view -- is synthesized in closed form with
full ground truth (there is no real depth sensor anywhere in this repo's
scope). What this script writes is not a depth recording; it is the tiny
SCENARIO description -- how many frames the sequence runs, at what rate,
and where the human's walk starts and turns around -- that main.cu loads
and then expands, frame by frame, into the robot's forward-kinematics pose
and the human's capsule geometry (see ../src/main.cu's build_scene()).
Everything else this project needs (the robot's link lengths, joint
sweep, the camera/cell geometry, the ISO/TS-15066-style formula
parameters) is the compile-time "model" documented once in
../src/kernels.cuh -- the same split project 08.01 uses for its plant
parameters vs. its loaded initial-condition scenario.

The DEFAULT values below are not arbitrary: they were chosen (and are
reproduced in ../src/kernels.cuh's SSM formula constants and the CSV row
values here) so that, with the compiled-in robot/camera model, the human's
walk drives the SSM state machine through a complete, clean
NORMAL -> REDUCED -> PROTECTIVE_STOP -> REDUCED -> NORMAL cycle with a
comfortable safety margin at both ends and a single unambiguous closest-
approach event -- verified numerically before this project's kernels were
even written (see the project's push-note / design notes) and then
verified AGAIN by the program itself every run (the analytic gates in
main.cu). Changing --frames/--rate/--human-start/--human-closest is
supported and safe; it will very likely also change WHEN (or whether) the
state machine transitions -- main.cu's gates will tell you honestly if a
new scenario no longer produces a clean cycle.

Usage
-----
    python make_synthetic.py                  # writes the committed default
    python make_synthetic.py --frames 300 --rate 30 \\
        --human-start -1.6 0.9 --human-closest 0.7 0.9
"""

import argparse
from pathlib import Path

DEFAULT_FRAMES = 240          # 8.0 s at the default rate
DEFAULT_RATE_HZ = 30.0        # depth-camera frame rate (SYSTEM_DESIGN.md §1.1: cameras run 30-60 Hz)
DEFAULT_HUMAN_START = (-1.6, 0.9)     # m, cell frame -- far corner of the walking lane
DEFAULT_HUMAN_CLOSEST = (0.7, 0.9)    # m, cell frame -- nearest point of the approach


def make_scenario_csv(frames: int, rate_hz: float,
                      human_start: tuple, human_closest: tuple,
                      out_path: Path) -> None:
    """Write the SSM scenario CSV main.cu loads.

    Parameters
    ----------
    frames        : total frames in the sequence (> 1).
    rate_hz       : depth-camera frame rate, Hz (> 0).
    human_start   : (x, y) in meters, cell frame -- the walk's start/end point.
    human_closest : (x, y) in meters, cell frame -- the walk's turnaround point.
    out_path      : destination CSV. Parent directories are created if missing.

    The human's path is a raised-cosine ("there and back") interpolation
    between these two points, driven by the SAME shared profile that also
    drives the robot's synchronized reach cycle -- see ../src/main.cu's
    reach_fraction()/build_scene(). This is scenario DATA (labeled
    synthetic, reproducible from this fixed command, no RNG anywhere in
    this project -- the whole pipeline is deterministic), not a recording.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        f.write("# SYNTHETIC scenario for project 21.04 (generated by scripts/make_synthetic.py)\n")
        f.write("# DIDACTIC -- feeds a non-certified SSM teaching pipeline; see ../src/kernels.cuh\n")
        f.write(f"# regenerate: python make_synthetic.py --frames {frames} --rate {rate_hz} "
                f"--human-start {human_start[0]} {human_start[1]} "
                f"--human-closest {human_closest[0]} {human_closest[1]}\n")
        f.write("# FRAMES,<n>                      total frames in the sequence\n")
        f.write("# RATE_HZ,<hz>                    depth-camera frame rate\n")
        f.write("# HUMAN_START,<x_m>,<y_m>         walk start/end point (cell frame)\n")
        f.write("# HUMAN_CLOSEST,<x_m>,<y_m>       walk turnaround point (cell frame)\n")
        f.write(f"FRAMES,{frames}\n")
        f.write(f"RATE_HZ,{rate_hz:.4f}\n")
        f.write(f"HUMAN_START,{human_start[0]:.4f},{human_start[1]:.4f}\n")
        f.write(f"HUMAN_CLOSEST,{human_closest[0]:.4f},{human_closest[1]:.4f}\n")

    duration_s = frames / rate_hz
    print(f"[make_synthetic] wrote scenario to {out_path} "
          f"({frames} frames @ {rate_hz:.1f} Hz = {duration_s:.2f} s, "
          f"human {human_start} -> {human_closest} -> {human_start}, labeled SYNTHETIC)")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    default_out = script_dir.parent / "data" / "sample" / "ssm_scenario.csv"

    parser = argparse.ArgumentParser(
        description="Generate the tiny synthetic SSM scenario for project 21.04 "
                    "(didactic speed-and-separation monitoring -- NOT a certified safety function).")
    parser.add_argument("--frames", type=int, default=DEFAULT_FRAMES,
                        help=f"total frames in the sequence (default {DEFAULT_FRAMES})")
    parser.add_argument("--rate", type=float, default=DEFAULT_RATE_HZ,
                        help=f"depth-camera frame rate, Hz (default {DEFAULT_RATE_HZ})")
    parser.add_argument("--human-start", type=float, nargs=2, default=list(DEFAULT_HUMAN_START),
                        metavar=("X_M", "Y_M"), help="walk start/end point, meters, cell frame")
    parser.add_argument("--human-closest", type=float, nargs=2, default=list(DEFAULT_HUMAN_CLOSEST),
                        metavar=("X_M", "Y_M"), help="walk turnaround point, meters, cell frame")
    parser.add_argument("--out", type=Path, default=default_out,
                        help="output CSV path (default: ../data/sample/ssm_scenario.csv)")
    args = parser.parse_args()

    if args.frames <= 1:
        parser.error("--frames must be > 1")
    if args.rate <= 0:
        parser.error("--rate must be > 0")

    make_scenario_csv(args.frames, args.rate,
                      tuple(args.human_start), tuple(args.human_closest),
                      args.out)


if __name__ == "__main__":
    main()
